Repository ExpressLRS/ExpressLRS, pull requests merged in 2021-12, with the labels that each got.

#1143 Increase STM32 emulated EEPROM commit delay
  src/src/common.cpp
  src/src/tx_main.cpp
Labels: pick

#1085 Add Axisflying THOR 2.4 TX Pro targets
  src/include/target/AXIS_THOR_2400_RX.h
  src/include/target/AXIS_THOR_2400_TX.h
  src/include/targets.h
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/FiveWayButton/FiveWayButton.cpp
  src/lib/FiveWayButton/FiveWayButton.h
  src/lib/GSENSOR/devGsensor.cpp
  src/lib/GSENSOR/devGsensor.h
  src/lib/GSENSOR/gsensor.cpp
  src/lib/GSENSOR/gsensor.h
  src/lib/GSENSOR/stk8baxx.cpp
  src/lib/GSENSOR/stk8baxx.h
  src/lib/MSP/msptypes.h
  src/lib/POWERMGNT/POWERMGNT.cpp
  src/lib/POWERMGNT/POWERMGNT.h
  src/lib/SCREEN/TFT_eSPI_User_Setup.h
  src/lib/SCREEN/devScreen.cpp
  src/lib/SCREEN/devScreen.h
  src/lib/SCREEN/logos.h
  src/lib/SCREEN/screen.cpp
  src/lib/SCREEN/screen.h
  src/lib/THERMAL/devThermal.cpp
  src/lib/THERMAL/devThermal.h
  src/lib/THERMAL/lm75a.cpp
  src/lib/THERMAL/lm75a.h
  src/lib/THERMAL/thermal.cpp
  src/lib/THERMAL/thermal.h
  src/platformio.ini
  src/src/tx_main.cpp
  src/targets/axis_2400.ini
Labels: V2.1

#1148 Enable WS2812_IS_GRB for ES24TX Pro
  src/include/target/HappyModel_ES24TX_Pro_Series_2400_TX.h
Labels: pick

#1146 Adding 5s delay after WiFi firmware upload
  src/html/scan.js
Labels: pick

#1147 Add guard around DEVICE_NAME for common headers
  src/include/native.h
  src/include/options.h
  src/include/target/BETAFPV_2400_RX.h
  src/include/target/BETAFPV_2400_TX.h
  src/include/target/BETAFPV_2400_TX_MICRO.h
  src/include/target/BETAFPV_900_TX.h
  src/include/target/BETAFPV_900_TX_MICRO.h
  src/include/target/DIY_2400_RX_ESP8285_SX1280.h
  src/include/target/DIY_2400_RX_PWMP.h
  src/include/target/DIY_2400_RX_STM32_CCG_Nano_v0_5.h
  src/include/target/DIY_2400_TX_ESP32_SX1280_E28.h
  src/include/target/DIY_2400_TX_ESP32_SX1280_LORA1280F27.h
  src/include/target/DIY_2400_TX_ESP32_SX1280_Mini.h
  src/include/target/DIY_2400_TX_ESP8285_SX1280.h
  src/include/target/DIY_900_RX_ESP8285_SX127x.h
  src/include/target/DIY_900_RX_HUZZAH_RFM95W.h
  src/include/target/DIY_900_RX_PWMP.h
  src/include/target/DIY_900_TX_ESP32_SX127x_E19.h
  src/include/target/DIY_900_TX_ESP32_SX127x_RFM95.h
  src/include/target/DIY_900_TX_TTGO_V1_SX127x.h
  src/include/target/DIY_900_TX_TTGO_V2_SX127x.h
  src/include/target/FM30_RX_MINI.h
  src/include/target/FM30_TX.h
  src/include/target/Frsky_RX_R9M.h
  src/include/target/Frsky_TX_R9M_LITE.h
  src/include/target/Frsky_TX_R9M_LITE_PRO.h
  src/include/target/GHOST_2400_TX_LITE.h
  src/include/target/GHOST_ATTO_2400_RX.h
  src/include/target/HGLRC_Hermes_2400_TX.h
  src/include/target/HappyModel_ES24TX_2400_TX.h
  src/include/target/HappyModel_ES24TX_Pro_Series_2400_TX.h
  src/include/target/HappyModel_TX_ES900TX.h
  src/include/target/HappyModel_TX_ES915TX.h
  src/include/target/MATEK_2400_RX.h
  src/include/target/NamimnoRC_FLASH_2400_OLED_TX.h
  src/include/target/NamimnoRC_FLASH_2400_RX.h
  src/include/target/NamimnoRC_FLASH_2400_TX.h
  src/include/target/NamimnoRC_VOYAGER_900_ESP_RX.h
  src/include/target/NamimnoRC_VOYAGER_900_OLED_TX.h
  src/include/target/NamimnoRC_VOYAGER_900_RX.h
  src/include/target/NamimnoRC_VOYAGER_900_TX.h
  src/include/target/QuadKopters_JR_2400_TX.h
  src/lib/CRSF/CRSF.cpp
  src/lib/CrsfProtocol/crsf_protocol.h
  src/lib/WIFI/devWIFI.cpp
  src/src/options.cpp
Labels: pick

#1074 Targets: add NamimnoRC FLASH ESP diversity receiver
  src/include/target/NamimnoRC_FLASH_2400_RX_ESP8285.h
  src/include/target/NamimnoRC_FLASH_2400_RX_STM32.h
  src/targets/namimnorc_2400.ini
Labels: V2.1

#1156 Fix for too early VTX MSP commands
  src/lib/VTX/devVTX.cpp
Labels: pick

#1155 Upgrade STM32 Arduino platform to 15.1 and support -flto flag
  src/targets/frsky.ini
Labels: V2.1

#1106 iFlight 2.4G and 900M Tx and Rx targets
  src/include/target/BETAFPV_900_TX.h
  src/include/target/iFlight_2400_RX.h
  src/include/target/iFlight_2400_TX.h
  src/include/target/iFlight_900_TX.h
  src/include/targets.h
  src/lib/BUTTON/devButton.cpp
  src/lib/BUTTON/devButton.h
  src/lib/LED/devLED.cpp
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/SX127xDriver/SX127xRegs.h
  src/platformio.ini
  src/targets/iFlight_2400.ini
  src/targets/iFlight_900.ini
Labels: V2.1

#1178 fix telemetry lost
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/SX127xDriver/SX127xRegs.h
Labels: pick

#1154 Device core affinity
  src/lib/CRSF/CRSF.cpp
  src/lib/CRSF/CRSF.h
  src/lib/CRSF/devCRSF.cpp
  src/lib/CRSF/devCRSF.h
  src/lib/DEVICE/device.cpp
  src/lib/DEVICE/device.h
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: V2.1

#1171 Fix custom startup melodies
  src/python/build_flags.py
Labels: pick

#1151 Menu Support and AXIS Targets
  src/include/options.h
  src/include/target/AXIS_THOR_2400_RX.h
  src/include/target/AXIS_THOR_2400_TX.h
  src/include/target/BETAFPV_2400_TX_MICRO.h
  src/include/target/BETAFPV_900_TX_MICRO.h
  src/include/target/GHOST_2400_TX.h
  src/include/target/GHOST_2400_TX_LITE.h
  src/include/target/NamimnoRC_FLASH_2400_OLED_TX.h
  src/include/target/NamimnoRC_VOYAGER_900_OLED_TX.h
  src/include/targets.h
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/GSENSOR/devGsensor.cpp
  src/lib/GSENSOR/devGsensor.h
  src/lib/GSENSOR/gsensor.cpp
  src/lib/GSENSOR/gsensor.h
  src/lib/GSENSOR/stk8baxx.cpp
  src/lib/GSENSOR/stk8baxx.h
  src/lib/LUA/devLUA.cpp
  src/lib/MSP/msptypes.h
  src/lib/OLED/OLED.cpp
  src/lib/OLED/OLED.h
  src/lib/OLED/XBMStrings.h
  src/lib/OLED/devOLED.cpp
  src/lib/POWERMGNT/POWERMGNT.cpp
  src/lib/POWERMGNT/POWERMGNT.h
  src/lib/SCREEN/FiveWayButton/FiveWayButton.cpp
  src/lib/SCREEN/FiveWayButton/FiveWayButton.h
  src/lib/SCREEN/OLED/XBMStrings.h
  src/lib/SCREEN/OLED/oledscreen.cpp
  src/lib/SCREEN/OLED/oledscreen.h
  src/lib/SCREEN/TFT/TFT_eSPI_User_Setup.h
  src/lib/SCREEN/TFT/logos.h
  src/lib/SCREEN/TFT/tftscreen.cpp
  src/lib/SCREEN/TFT/tftscreen.h
  src/lib/SCREEN/devScreen.cpp
  src/lib/SCREEN/devScreen.h
  src/lib/SCREEN/screen.cpp
  src/lib/SCREEN/screen.h
  src/lib/THERMAL/devThermal.cpp
  src/lib/THERMAL/devThermal.h
  src/lib/THERMAL/lm75a.cpp
  src/lib/THERMAL/lm75a.h
  src/lib/THERMAL/thermal.cpp
  src/lib/THERMAL/thermal.h
  src/lib/WIFI/devWIFI.cpp
  src/lib/logging/VA_OPT.h
  src/lib/logging/logging.h
  src/platformio.ini
  src/src/options.cpp
  src/src/tx_main.cpp
  src/targets/axis_2400.ini
Labels: enhancement, V2.1

#1149 Add firmware.bin to webui
  src/html/rx_index.html
  src/html/tx_index.html
  src/lib/WIFI/devWIFI.cpp
Labels: V2.1

#1199 Setting TFT lib version requirement
  src/targets/axis_2400.ini
Labels: V2.1

#1201 Add support for chunked msp responses
  src/lib/Telemetry/telemetry.cpp
Labels: pick

#1200 Adds Region to Web & Lua
  src/python/build_flags.py
  src/python/build_html.py
Labels: V2.1

#1202 Adding betaFPV 2.4 micro 1000mw target
  src/include/target/BETAFPV_2400_TX_MICRO.h
  src/targets/betafpv_2400.ini
Labels: enhancement, V2.1

#1188 iFlight fix 2400TX output // add LED cases
  src/include/target/iFlight_2400_TX.h
  src/lib/LED/devLED.cpp
Labels: V2.1

#1222 Updating power change to Screen correctly
  src/lib/POWERMGNT/POWERMGNT.cpp
  src/lib/POWERMGNT/POWERMGNT.h
Labels: V2.1

#1225 Display wifi update page when in wifi mode
  src/lib/SCREEN/devScreen.cpp
  src/lib/SCREEN/screen.cpp
  src/lib/SCREEN/screen.h
Labels: V2.1

#1217 Use sans-serif fonts for OLED
  src/lib/SCREEN/OLED/oledscreen.cpp
  src/lib/SCREEN/screen.cpp
Labels: V2.1
