Repository ExpressLRS/ExpressLRS, pull requests merged in 2021-09, with the labels that each got.

#878 Add inverted CRSF output to ESP8266 receivers
  src/src/rx_main.cpp
  src/user_defines.txt
Labels: needs doc, release notes

#883 Perform more complete RF shutdown when entering WebUpdate mode
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/SX127xDriver/SX127xHal.cpp
  src/lib/SX1280Driver/SX1280.cpp
  src/lib/SX1280Driver/SX1280_hal.cpp
  src/src/ESP32_WebUpdate.cpp
  src/src/ESP32_WebUpdate.h
  src/src/ESP8266_WebUpdate.cpp
  src/src/ESP8266_WebUpdate.h
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: release notes

#894 Changed the default dynamic power thresholds 15/21
  src/src/tx_main.cpp
Labels: needs doc

#888 Semi-connected ModelMatch
  src/html/rx_index.html
  src/lib/OTA/OTA.h
  src/src/common.h
  src/src/config.cpp
  src/src/config.h
  src/src/options.cpp
  src/src/rx_main.cpp
  src/src/tx_main.cpp
  src/user_defines.txt
Labels: needs doc

#891 Make ESP8266 timer consistent with STM32 behavior
  src/lib/HWTIMER/ESP8266_hwTimer.cpp
  src/lib/HWTIMER/STM32_hwTimer.cpp
Labels: bug

#905 TelemBurst sending one extra packet per burst
  src/src/rx_main.cpp
Labels: pick to v1.2
