Repository ExpressLRS/ExpressLRS, pull requests merged in 2021-11, with the labels that each got.

#998 Add support for PWM receiver output
  src/boards/esp8285-8285.json
  src/html/main.css
  src/html/rx_index.html
  src/html/scan.js
  src/include/target/DIY_2400_RX_PWMP.h
  src/include/target/DIY_900_RX_PWMP.h
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/CRSF/CRSF.cpp
  src/lib/CRSF/CRSF.h
  src/lib/HWTIMER/ESP8266_hwTimer.cpp
  src/lib/HWTIMER/ESP8266_hwTimer.h
  src/lib/WIFI/devWIFI.cpp
  src/lib/logging/logging.h
  src/src/rx_main.cpp
  src/targets/common.ini
  src/targets/diy_2400.ini
  src/targets/diy_900.ini
  src/targets/imrc.ini
  src/variants/GHOST_ATTO/variant.h
Labels: needs doc, release notes

#1035 Backport ES900RX upload via UART target
  src/targets/happymodel_900.ini
Labels: v1.2

#1043 cherry pick of replaced duplex_set_tx with noInterrupt (#1042)
  src/lib/CRSF/CRSF.cpp
Labels: v1.2

#1052 Add Lua power fan threshold
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/LUA/devLUA.cpp
  src/lib/POWERMGNT/POWERMGNT.cpp
  src/lib/POWERMGNT/POWERMGNT.h
  src/src/tx_main.cpp
Labels: needs doc, release notes

#1080 Prevent crash when using BACK item when lua is reloading
  src/lib/CrsfProtocol/crsf_protocol.h
  src/lib/LUA/lua.cpp
  src/lua/elrsV2.lua
Labels: pick

#1093 Shorten Namimno OLEDs to 15 chars
  src/include/target/NamimnoRC_FLASH_2400_OLED_TX.h
  src/include/target/NamimnoRC_VOYAGER_900_OLED_TX.h
Labels: pick

#1091 fix LUA render on NV14
  src/lua/elrsV2.lua
Labels: pick

#1086 Forgot to remove IRQ clear code
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/SX1280Driver/SX1280.cpp
Labels: pick

#1096 Use two param popupConfirmation on FreedomTX
  src/lua/elrsV2.lua
Labels: pick

#1099 do not process start wifi MSP on stm32
  src/src/rx_main.cpp
Labels: pick

#1092 Prevent going to 1:2 ratio when disconnected and entering Lua
  src/include/native.h
  src/lib/CRSF/CRSF.cpp
  src/lib/CRSF/CRSF.h
  src/lib/CrsfProtocol/crsf_protocol.h
  src/src/tx_main.cpp
  src/test/msp_native/encapsulated_msp_tests.cpp
Labels: pick

#1097 Wrong firmware version displayed on web update
  src/html/esp32webupdate/compressed.html
  src/html/esp32webupdate/index.html
  src/src/tx_main.cpp
Labels: v1.2

#1100 Minor Lua fixes following RC2
  src/lua/elrsV2.lua
  src/src/tx_main.cpp
Labels: pick

#1060 adds DIY_BLE_JOYSTICK_via_UART target
  src/platformio.ini
  src/src/options.cpp
  src/src/tx_main.cpp
  src/targets/diy_ble_joystick.ini
Labels: V2.1

#1101 Perform shell escaping on build args
  src/python/build_flags.py
  src/targets/diy_2400.ini
Labels: pick

#1109 Only rebuild HTML header if changed
  src/python/build_html.py
Labels: pick

#1112 devLED copy paste bug
  src/lib/LED/devLED.h
Labels: pick

#1115 Move all build git queries to one function
  src/python/build_flags.py
  src/python/build_html.py
  src/python/elrs_helpers.py
Labels: pick

#1117 Lock FM30 TX antenna to left
  src/include/target/FM30_TX.h
  src/src/tx_main.cpp
Labels: pick

#1118 Don't abort if we're asking the user!
  src/lib/WIFI/devWIFI.cpp
Labels: pick

#1113 Start dynamic power low instead of high
  src/src/tx_main.cpp
Labels: pick, needs doc

#1119 Stop DEBUG_CRSF_NO_OUTPUT sending MSP
  src/lib/CRSF/CRSF.cpp
Labels: pick

#1135 correct elrs logo
  src/html/flag.svg
  src/html/logo.svg
  src/html/rx_index.html
  src/html/tx_index.html
  src/lib/WIFI/devWIFI.cpp
  src/python/build_html.py
Labels: pick

#1127 Abort current telem receive if about to commit
  src/src/tx_main.cpp
Labels: pick

#1131 Lua: Allow changing a value when it is set to ERR
  src/lua/elrsV2.lua
Labels: pick

#1133 R9M using wrong Idle method and EEPROM speedup
  src/include/target/Frsky_TX_R9M.h
  src/lib/EEPROM/elrs_eeprom.cpp
  src/src/tx_main.cpp
Labels: pick

#1128 Move all sendLinkStatisticsToFC() to one place
  src/lib/SX127xDriver/SX127x.cpp
  src/src/rx_main.cpp
Labels: pick
