Repository ExpressLRS/ExpressLRS, pull requests merged in 2022-06, with the labels that each got.

#1510 Bump to share
  src/include/rxtx_common.h
  src/lib/GSENSOR/devGsensor.cpp
  src/lib/GSENSOR/gsensor.cpp
  src/lib/GSENSOR/gsensor.h
  src/lib/GSENSOR/stk8baxx.h
  src/lib/LUA/lua.cpp
  src/lib/LUA/lua.h
  src/lib/LUA/rx_devLUA.cpp
  src/lib/MSP/msptypes.h
  src/lib/logging/logging.cpp
  src/src/rx_main.cpp
  src/src/rxtx_common.cpp
  src/src/tx_main.cpp
Labels: V3.0

#1457 ESP8266 as DupleTX
  src/hardware/TX/DIY 2400 DupleTX ESP.json
  src/hardware/targets.json
  src/include/common.h
  src/include/target/DIY_2400_TX_ESP8285_SX1280.h
  src/include/target/Unified_ESP8285_TX.h
  src/include/targets.h
  src/lib/CRSF/CRSF.cpp
  src/lib/CRSF/CRSF.h
  src/lib/CrsfProtocol/crsf_protocol.h
  src/lib/HWTIMER/ESP8266_hwTimer.cpp
  src/lib/LED/devLED.cpp
  src/lib/LUA/tx_devLUA.cpp
  src/lib/OPTIONS/hardware.cpp
  src/lib/OPTIONS/options.cpp
  src/lib/POWERMGNT/POWERMGNT.cpp
  src/lib/WIFI/devWIFI.cpp
  src/lib/logging/logging.cpp
  src/lib/logging/logging.h
  src/src/rx_main.cpp
  src/src/tx_main.cpp
  src/targets/diy_2400.ini
  src/targets/unified.ini
Labels: V3.0

#1526 ESP32 PICO RX including the kitchen sink!
  src/hardware/RX/Frank 2400.json
  src/hardware/RX/Generic 2400 VTX.json
  src/hardware/targets.json
  src/html/hardware.html
  src/html/options.html
  src/include/hardware.h
  src/include/target/Unified_ESP32_TX.h
  src/include/target/Unified_ESP8285_RX.h
  src/lib/CRSF/CRSF.cpp
  src/lib/CRSF/CRSF.h
  src/lib/CRSF/devCRSF.h
  src/lib/CRSF/devCRSF_rx.cpp
  src/lib/CRSF/devCRSF_tx.cpp
  src/lib/FHSS/FHSS.cpp
  src/lib/HWTIMER/ESP32_hwTimer.cpp
  src/lib/HWTIMER/ESP32_hwTimer.h
  src/lib/HWTIMER/ESP8266_hwTimer.cpp
  src/lib/HWTIMER/ESP8266_hwTimer.h
  src/lib/LED/devRGB.cpp
  src/lib/LQCALC/LQCALC.h
  src/lib/OPTIONS/hardware.cpp
  src/lib/ServoOutput/ServoMgr.cpp
  src/lib/ServoOutput/ServoMgr.h
  src/lib/ServoOutput/devServoOutput.cpp
  src/lib/ServoOutput/devServoOutput.h
  src/lib/TCPSOCKET/tcpsocket.cpp
  src/lib/TCPSOCKET/tcpsocket.h
  src/lib/Telemetry/telemetry.cpp
  src/lib/VTXSPI/devVTXSPI.cpp
  src/python/UnifiedConfiguration.py
  src/python/build_html.py
  src/src/rx_main.cpp
  src/targets/common.ini
  src/targets/unified.ini
Labels: V3.0

#1606 Return size optimization to STM32
  src/include/target/FM30_TX.h
  src/lib/logging/logging.h
  src/targets/common.ini
Labels: V3.0

#1555 Diversity 2.4GHz (SX1280) Rx... aka Medley
  src/hardware/RX/Generic 2400 Diversity and VTx.json
  src/hardware/RX/Generic 2400 Diversity.json
  src/hardware/targets.json
  src/html/hardware.html
  src/include/hardware.h
  src/include/target/Unified_ESP32_TX.h
  src/include/target/Unified_ESP8285_RX.h
  src/include/target/Unified_ESP8285_TX.h
  src/include/targets.h
  src/lib/OPTIONS/hardware.cpp
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/SX127xDriver/SX127x.h
  src/lib/SX1280Driver/SX1280.cpp
  src/lib/SX1280Driver/SX1280.h
  src/lib/SX1280Driver/SX1280_Regs.h
  src/lib/SX1280Driver/SX1280_hal.cpp
  src/lib/SX1280Driver/SX1280_hal.h
  src/lib/SX12xxDriverCommon/SX12xxDriverCommon.h
  src/platformio.ini
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: V3.0

#1599 Automatic telemetry modes Standard and NoTelemOnArm
  src/html/index.html
  src/include/common.h
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/LUA/tx_devLUA.cpp
  src/lib/OPTIONS/options.cpp
  src/lib/OPTIONS/options.h
  src/lib/SCREEN/display.cpp
  src/python/binary_configurator.py
  src/python/build_flags.py
  src/src/common.cpp
  src/src/rx_main.cpp
  src/src/tx_main.cpp
  src/user_defines.txt
Labels: needs doc, V3.0

#1572 Full resolution mode
  src/include/common.h
  src/include/native.h
  src/include/rxtx_common.h
  src/lib/BLE/devBLE.cpp
  src/lib/Backpack/devBackpack.cpp
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/CRC/crc.cpp
  src/lib/CRC/crc.h
  src/lib/CRSF/CRSF.cpp
  src/lib/CRSF/CRSF.h
  src/lib/CrsfProtocol/crsf_protocol.h
  src/lib/FHSS/FHSS.cpp
  src/lib/GSENSOR/devGsensor.cpp
  src/lib/GSENSOR/devGsensor.h
  src/lib/LED/devRGB.cpp
  src/lib/LUA/lua.cpp
  src/lib/LUA/tx_devLUA.cpp
  src/lib/MSP/msptypes.h
  src/lib/OTA/OTA.cpp
  src/lib/OTA/OTA.h
  src/lib/SCREEN/TFT/tftdisplay.cpp
  src/lib/SCREEN/devScreen.cpp
  src/lib/SCREEN/devScreen.h
  src/lib/SCREEN/display.cpp
  src/lib/SCREEN/menu.cpp
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/SX127xDriver/SX127x.h
  src/lib/SX1280Driver/SX1280.cpp
  src/lib/SX1280Driver/SX1280.h
  src/lib/SX1280Driver/SX1280_hal.cpp
  src/lib/SX1280Driver/SX1280_hal.h
  src/lib/SX12xxDriverCommon/SX12xxDriverCommon.h
  src/lib/ServoOutput/devServoOutput.cpp
  src/lib/StubbornReceiver/stubborn_receiver.cpp
  src/lib/StubbornReceiver/stubborn_receiver.h
  src/lib/StubbornSender/stubborn_sender.cpp
  src/lib/StubbornSender/stubborn_sender.h
  src/lib/THERMAL/devThermal.cpp
  src/lib/THERMAL/devThermal.h
  src/lib/TelemetryProtocol/telemetry_protocol.h
  src/lib/VTX/devVTX.cpp
  src/lib/VTXSPI/devVTXSPI.cpp
  src/lib/VTXSPI/devVTXSPI.h
  src/lib/logging/logging.h
  src/lua/elrsV2.lua
  src/src/common.cpp
  src/src/rx_main.cpp
  src/src/tx_main.cpp
  src/test/test_crc/test_crc.cpp
  src/test/test_ota/crsf_sysmocks.cpp
  src/test/test_ota/crsf_sysmocks.h
  src/test/test_ota/test_switches.cpp
  src/test/test_stubborn/test_stubborn.cpp
Labels: V3.0

#1618 Fix some targets using int for booleans in the json file
  src/hardware/RX/BETAFPV Nano 2400.json
  src/hardware/RX/Frank 2400.json
  src/hardware/RX/Generic 2400 Diversity and VTx.json
  src/hardware/RX/Generic 2400 Diversity.json
  src/hardware/RX/Generic 2400 VTX.json
  src/hardware/RX/Generic 2400 Whoop Rx and VTx.json
Labels: V3.0

#1617 Cleanup the Namimno RX target files
  src/hardware/RX/Generic 2400.json
  src/hardware/RX/Namimno FLASH 2400.json
  src/hardware/RX/Namimno VOYAGER 900.json
  src/hardware/targets.json
Labels: V3.0

#1613 Display WiFi running screen on OLED/TFT when WiFi auto starts
  src/lib/SCREEN/devScreen.cpp
  src/lib/SCREEN/fsm.cpp
  src/lib/SCREEN/fsm.h
  src/lib/SCREEN/menu.cpp
Labels: V3.0

#1621 Cosmetic fix for issue #1426
  src/lib/SX127xDriver/SX127x.cpp
Labels: V3.0

#1614 Fix firmware download on WiFi
  src/lib/WIFI/devWIFI.cpp
Labels: V3.0 :rocket:

#1620 Add button definition to RXs
  src/hardware/RX/Frank 2400.json
  src/hardware/RX/Generic 2400 Diversity and VTx.json
  src/hardware/RX/Generic 2400 Diversity.json
  src/hardware/RX/Generic 2400 Whoop Rx and VTx.json
  src/hardware/RX/Generic 900.json
  src/hardware/RX/MATEK 2400.json
  src/hardware/RX/iFlight 2400.json
Labels: V3.0 :rocket:

#1615 update adjustPacketRateForBaud for new rf modes
  src/include/common.h
  src/src/common.cpp
  src/src/tx_main.cpp
Labels: V3.0 :rocket:

#1632 Fix RX LUA crashing on commit
  src/src/rx_main.cpp
Labels: bug :bug:, V3.0 :rocket:

#1629 Fix slow TLMBoost causing TX->RX MSP timeouts
  src/lib/StubbornReceiver/stubborn_receiver.cpp
  src/lib/StubbornSender/stubborn_sender.cpp
  src/src/tx_main.cpp
Labels: bug :bug:, V3.0 :rocket:

#1529 SNR-based dynamic power system, refactor to new unit
  src/include/common.h
  src/include/dynpower.h
  src/lib/MeanAccumulator/MeanAccumulator.h
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/SX127xDriver/SX127x.h
  src/lib/SX1280Driver/SX1280.cpp
  src/lib/SX1280Driver/SX1280.h
  src/lib/SX12xxDriverCommon/SX12xxDriverCommon.h
  src/src/common.cpp
  src/src/dynpower.cpp
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: needs doc :book:, V3.0 :rocket:

#1627 Extracting/Normalising RX targets that have Power Amps
  src/hardware/RX/Generic 2400 PA Diversity.json
  src/hardware/RX/Generic 2400 PA.json
  src/hardware/RX/Vantac 2400.json
  src/hardware/RX/iFlight 2400.json
  src/hardware/targets.json
Labels: bug :bug:, V3.0 :rocket:

#1636 I forgot about the mDNS options!
  src/lib/OPTIONS/options.cpp
  src/lib/OPTIONS/options.h
  src/lib/WIFI/devWIFI.cpp
Labels: bug :bug:, V3.0 :rocket:

#1644 Return LoRa operation after IRQ changes
  src/lib/SX1280Driver/SX1280.cpp
Labels: bug :bug:, V3.0 :rocket:

#1646 Display bugs: F500, TLM Ratio, Fullres modes
  src/lib/SCREEN/OLED/oleddisplay.cpp
  src/lib/SCREEN/TFT/tftdisplay.cpp
  src/lib/SCREEN/display.cpp
  src/lib/SCREEN/menu.cpp
  src/lib/SCREEN/menu.h
Labels: bug :bug:, V3.0 :rocket:

#1626 Adds a rx option to force disable tlm
  src/html/elrs.css
  src/html/index.html
  src/html/scan.js
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/WIFI/devWIFI.cpp
  src/src/rx_main.cpp
Labels: enhancement :magic_wand:, V3.0 :rocket:

#1642 Set Sync Address Control to zero bit errors permissible
  src/lib/SX1280Driver/SX1280.cpp
  src/lib/SX1280Driver/SX1280_Regs.h
Labels: enhancement :magic_wand:

#1647 SetRFLinkRate must execute if only switchmode changes
  src/src/tx_main.cpp
Labels: bug :bug:, V3.0 :rocket:

#1645 Resolve RX crash when changing ModelID from Lua
  src/include/common.h
  src/lib/WIFI/devWIFI.cpp
  src/src/rx_main.cpp
Labels: bug :bug:, V3.0 :rocket:

#1579 fix tx diversity antenna for tlm reception
  src/src/tx_main.cpp
Labels: bug :bug:, V3.0 :rocket:

#1643 2.x to 3.0 Config Update
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/CONFIG/config_legacy.h
  src/lib/WIFI/devWIFI.cpp
  src/lib/elrs_eeprom/elrs_eeprom.cpp
Labels: V3.0 :rocket:

#1650 Don't descale FreqCorrection stored in SNR
  src/lib/SX1280Driver/SX1280_Regs.h
  src/src/tx_main.cpp
  src/user_defines.txt
Labels: bug :bug:

#1651 Second 3.0 Config Attempt
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
Labels: V3.0 :rocket:

#1655 Remove extra ClearIrqStatus call
  src/lib/SX1280Driver/SX1280.cpp
Labels: V3.0 :rocket:

#1656 fix binding after OTA change
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: bug :bug:, V3.0 :rocket:

#1659 Team900 not setting packet length
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/SX127xDriver/SX127x.h
Labels: bug :bug:, V3.0 :rocket:
