Repository ExpressLRS/ExpressLRS, pull requests merged in 2022-11, with the labels that each got.

#1924 Update u8g2, it got removed from the registry!
  src/targets/common.ini
Labels: bugfixes :lady_beetle:, V3.1 :thinking:

#1933 Fix error in initial network setting
  .github/workflows/build.yml
  src/html/scan.js
  src/python/serve_html.py
Labels: bugfixes :lady_beetle:, V3.1 :thinking:

#1930 Scale PWM failsafe timeout with packet rate
  src/include/rxtx_intf.h
  src/lib/ServoOutput/devServoOutput.cpp
  src/src/rx_main.cpp
Labels: V3.1 :thinking:

#1921 Change binding to use deferExecution() for the 2s delay.
  src/src/rx_main.cpp
Labels: V3.1 :thinking:

#1850 Add high pwm freq and duty mode support
  src/.clang-format
  src/html/scan.js
  src/include/common.h
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/LUA/rx_devLUA.cpp
  src/lib/ServoOutput/ServoMgr.cpp
  src/lib/ServoOutput/ServoMgr.h
  src/lib/ServoOutput/devServoOutput.cpp
  src/lib/ServoOutput/devServoOutput.h
Labels: enhancement :magic_wand:, V3.1 :thinking:

#1938 3.x merge to master
  src/include/target/FM30_TX.h
  src/lib/CRSF/devCRSF_rx.cpp
  src/src/tx_main.cpp
  src/targets/quadkopters_2400.ini
Labels: DO NOT SQUASH MERGE, V3.1 :thinking:

#1939 Adds some missing targets
  src/hardware/targets.json
  src/targets/betafpv_2400.ini
Labels: V3.1 :thinking:

#1940 Add Radiomaster Ranger targets
  src/hardware/TX/Radiomaster Ranger Micro.json
  src/hardware/TX/Radiomaster Ranger.json
  src/hardware/targets.json
  src/targets/radiomaster_2400.ini
Labels: new target :dart:, V3.1 :thinking:

#1937 Allow resetting temporary power level via OLED and Lua
  src/lib/LUA/tx_devLUA.cpp
  src/lib/SCREEN/menu.cpp
  src/src/tx_main.cpp
Labels: V3.1 :thinking:

#1942 revert SX1280_REG_FLRC_SYNC_ADDR_CTRL
  src/lib/SX1280Driver/SX1280.cpp
  src/lib/SX1280Driver/SX1280_Regs.h
Labels: V3.1 :thinking:

#1914 Gemini
  src/hardware/TX/Generic 2400 Gemini.json
  src/hardware/targets.json
  src/include/common.h
  src/lib/Backpack/devBackpack.cpp
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/FHSS/FHSS.h
  src/lib/LBT/LBT.cpp
  src/lib/LBT/LBT.h
  src/lib/LUA/rx_devLUA.cpp
  src/lib/LUA/tx_devLUA.cpp
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/SX127xDriver/SX127x.h
  src/lib/SX1280Driver/SX1280.cpp
  src/lib/SX1280Driver/SX1280.h
  src/lib/SX1280Driver/SX1280_hal.cpp
  src/lib/SX1280Driver/SX1280_hal.h
  src/lib/SX12xxDriverCommon/SX12xxDriverCommon.h
  src/src/common.cpp
  src/src/rx_main.cpp
  src/src/tx_main.cpp
  src/targets/diy_2400.ini
Labels: V3.2 :beer:

#1961 Fix windows build
  src/lib/OTA/OTA.h
  src/targets/common.ini
Labels: V3.1 :thinking:

#1964 set config defaults when flashing a previous version
  src/lib/CONFIG/config.cpp
Labels: V3.1 :thinking:

#1963 Fix config upgrade
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/CONFIG/config_legacy.h
Labels: V3.1 :thinking:

#1962 Fix PWM RX lua
  src/lib/LUA/rx_devLUA.cpp
Labels: V3.1 :thinking:
