Repository ExpressLRS/ExpressLRS, pull requests merged in 2022-01, with the labels that each got.

#1213 Send VTX Power only if not zero
  src/lib/CRSF/CRSF.cpp
  src/lib/MSP/msptypes.h
  src/lib/VTX/devVTX.cpp
Labels: V2.1

#1221 Bugfix - index was not compared to the provided min
  src/lib/SCREEN/screen.cpp
Labels: V2.1

#1255 Add hysteresis to TX fan
  src/lib/LUA/devLUA.cpp
  src/lib/POWERMGNT/POWERMGNT.cpp
  src/lib/POWERMGNT/POWERMGNT.h
  src/lib/THERMAL/devThermal.cpp
  src/lib/THERMAL/devThermal.h
  src/src/tx_main.cpp
  src/user_defines.txt
Labels: needs doc, V2.1

#1258 Fix RSSI calculation when SNR <0
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/SX1280Driver/SX1280.cpp
Labels: V2.1

#1264 Define GRB for devices that have the GRB LED
  src/include/target/AXIS_THOR_2400_TX.h
  src/include/target/BETAFPV_2400_TX_MICRO.h
  src/include/target/BETAFPV_900_TX_MICRO.h
Labels: V2.1

#1271 No External EEPROM bug on STM32 based TX
  src/src/tx_main.cpp
Labels: V2.1

#1270 Fixing the serial out for ghost tx modules
  src/src/tx_main.cpp
Labels: V2.1

#1267 Screen updates
  src/lib/SCREEN/OLED/oledscreen.cpp
  src/lib/SCREEN/OLED/oledscreen.h
  src/lib/SCREEN/TFT/tftscreen.cpp
  src/lib/SCREEN/TFT/tftscreen.h
  src/lib/SCREEN/devScreen.cpp
  src/lib/SCREEN/screen.cpp
  src/lib/SCREEN/screen.h
Labels: V2.1

#1285 FIFO protection
  src/include/native.h
  src/lib/CRSF/CRSF.cpp
  src/lib/CRSF/CRSF.h
  src/lib/FIFO/FIFO.cpp
  src/lib/FIFO/FIFO.h
  src/test/fifo_native/test_fifo.cpp
Labels: V2.1

#1286 Dynamic Power Enhancement
  src/src/tx_main.cpp
Labels: V2.1

#1291 Ghost tx lite patch
  src/include/target/GHOST_2400_TX.h
  src/lib/SCREEN/OLED/oledscreen.cpp
Labels: V2.1

#1288 Set radio timeout when doing telemetry RX
  src/include/common.h
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/SX127xDriver/SX127x.h
  src/lib/SX1280Driver/SX1280.cpp
  src/lib/SX1280Driver/SX1280.h
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: V2.1

#1298 Fix FrSky LUA
  src/lib/CRSF/CRSF.cpp
Labels: V2.1

#1161 Add EU compliant 2.4 region - limited to 10mw
  src/lib/LUA/devLUA.cpp
  src/lib/POWERMGNT/POWERMGNT.h
  src/python/build_flags.py
  src/user_defines.txt
Labels: V2.2

#1287 Full Duplex TX module
  .github/workflows/build.yml
  src/include/target/DIY_2400_TX_DUPLETX_TX.h
  src/include/target/GHOST_2400_TX.h
  src/include/targets.h
  src/lib/Backpack/devBackpack.cpp
  src/lib/Backpack/devBackpack.h
  src/lib/CRSF/CRSF.cpp
  src/lib/CRSF/CRSF.h
  src/lib/CRSF/devCRSF.cpp
  src/lib/DEVICE/device.cpp
  src/lib/DEVICE/device.h
  src/lib/POWERMGNT/POWERMGNT.cpp
  src/lib/POWERMGNT/POWERMGNT.h
  src/lib/POWER_DETECT/devPDET.cpp
  src/lib/POWER_DETECT/devPDET.h
  src/lib/VTX/devVTX.cpp
  src/lib/WIFI/devWIFI.cpp
  src/lib/logging/logging.h
  src/python/ETXinitPassthrough.py
  src/python/build_env_setup.py
  src/src/tx_main.cpp
  src/targets/diy_2400.ini
Labels: V2.2

#1296 Using clang microsoft format for this project
  src/.clang-format
Labels: For Discussion

#1294 [MENU/ JOYSTICK] adding fuzz value array
  src/lib/SCREEN/FiveWayButton/FiveWayButton.cpp
  src/lib/SCREEN/FiveWayButton/FiveWayButton.h
  src/lib/SCREEN/devScreen.cpp
Labels: V2.2

#1322 Create BLE as needed to prevent double inits
  src/lib/BLE/devBLE.cpp
Labels: pick, bugfixes

#1321 Enter WiFi update mode looks bad on 128x64 devices.
  src/lib/LUA/devLUA.cpp
Labels: pick, bugfixes

#1289 Add Vantac Lite TX and RX Targets
  src/include/target/Vantac_2400_RX.h
  src/include/target/Vantac_Lite_2400_TX.h
  src/platformio.ini
  src/targets/vantac_2400.ini
Labels: Needs Testing, new target

#1308 update web server to resolve deprecation, limit version of nimble lib
  src/targets/common.ini
Labels: pick, bugfixes

#1351 Improve rom bootloader upload reliability
  src/python/BFinitPassthrough.py
Labels: V2.1

#1212 Disable TX PA between packets
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/SX127xDriver/SX127xHal.cpp
  src/lib/SX1280Driver/SX1280.cpp
  src/lib/SX1280Driver/SX1280_hal.cpp
Labels: V3.0
