Repository ExpressLRS/ExpressLRS, pull requests merged in 2022-07, with the labels that each got.

#1634 Add new Jumper AION 2400 target
  src/hardware/TX/Jumper T-Lite.json
  src/hardware/targets.json
  src/targets/Jumper_2400.ini
Labels: V3.0 :rocket:, new target :dart:

#1661 Team2.4 50Hz to SF8
  src/lib/SX1280Driver/SX1280.cpp
  src/src/common.cpp
Labels: V3.0 :rocket:

#1664 Fix version number parsing
  src/lib/CRSF/CRSF.cpp
  src/lib/OPTIONS/options.cpp
  src/test/test_crsf/test_crsf.cpp
Labels: bug :bug:, V3.0 :rocket:

#1662 Add help text and indicator icons to the hardware.html page
  src/html/hardware.html
  src/html/hardware.js
  src/include/hardware.h
  src/include/target/Unified_ESP32_TX.h
  src/include/target/Unified_ESP8285_RX.h
  src/lib/OPTIONS/hardware.cpp
Labels: V3.1 :thinking:

#1672 Display warning/error when changing packet and baud-rate too low
  src/lib/LUA/lua.cpp
  src/lib/LUA/lua.h
  src/lib/LUA/tx_devLUA.cpp
Labels: V3.0 :rocket:

#1671 Default values not displayed in Web-UI
  src/lib/OPTIONS/options.cpp
Labels: bug :bug:, V3.0 :rocket:

#1674 Remove 8285 DIY_2400_RX_VTX target
  src/hardware/RX/Generic 2400 VTX.json
  src/hardware/targets.json
  src/targets/diy_2400.ini
Labels: V3.0 :rocket:

#1675 R9MM RX resetting config on every reboot
  src/src/rxtx_common.cpp
Labels: V3.0 :rocket:

#1663 Convergence of Antenna control pin names between TX and RX
  src/hardware/RX/Generic 2400 PA Diversity.json
  src/html/hardware.html
  src/include/hardware.h
  src/include/target/FM30_RX_MINI.h
  src/include/target/Frsky_RX_R9M.h
  src/include/target/GHOST_2400_TX.h
  src/include/target/Unified_ESP32_TX.h
  src/include/target/Unified_ESP8285_RX.h
  src/include/targets.h
  src/lib/CONFIG/config.cpp
  src/lib/LUA/rx_devLUA.cpp
  src/lib/OPTIONS/hardware.cpp
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: V3.0 :rocket:

#1673 XOR major version number with OtaCrcInitializer and macSeed
  src/include/common.h
  src/lib/OTA/OTA.cpp
  src/src/common.cpp
Labels: V3.0 :rocket:

#1680 Update Lua file name
  src/lua/README.md
  src/lua/elrsV3.lua
Labels: V3.0 :rocket:

#1685 Fix issue with WIFI upload reporting success when upload fails
  src/python/upload_via_esp8266_backpack.py
Labels: bug :bug:, V3.0 :rocket:

#1683 Enable DCDC only when enabled
  src/lib/SX1280Driver/SX1280.cpp
Labels: bug :bug:, V3.0 :rocket:

#1696 Increase AION Nano RIGHT joystick value to 70
  src/hardware/TX/Jumper AION Nano.json
Labels: V3.0 :rocket:

#1692 Adjust T-Lite power levels with power meter
  src/hardware/TX/Jumper T-Lite.json
Labels: V3.0 :rocket:

#1684 Fix LED not showing WIFI mode when started from Binding mode
  src/lib/BUTTON/devButton.cpp
  src/lib/LUA/tx_devLUA.cpp
  src/lib/SCREEN/menu.cpp
  src/lib/WIFI/devWIFI.cpp
  src/src/rx_main.cpp
Labels: bug :bug:, V3.0 :rocket:

#1700 I2C fix for ESP devices
  src/src/rxtx_common.cpp
Labels: bug :bug:, V3.0 :rocket:

#1688 Fix the default led on R9M
  src/lib/LED/devLED.cpp
Labels: bug :bug:, V3.0 :rocket:

#1703 Add CORS headers to web UI for web flasher
  src/lib/WIFI/devWIFI.cpp
Labels: enhancement :magic_wand:, V3.0 :rocket:

#1706 Fix for FHSS hopping where freq_count is a power of 2
  src/lib/FHSS/FHSS.cpp
  src/lib/FHSS/FHSS.h
Labels: bug :bug:, V3.0 :rocket:

#1693 Target config cleanup
  .github/workflows/build.yml
  src/hardware/RX/Generic 2400 PA Diversity.json
  src/hardware/RX/Generic 2400 PA.json
  src/hardware/targets.json
  src/lib/OPTIONS/options.cpp
  src/lib/OPTIONS/options.h
  src/python/BFinitPassthrough.py
  src/python/UARTupload.py
  src/python/UnifiedConfiguration.py
  src/python/binary_configurator.py
  src/python/binary_flash.py
  src/python/firmware.py
  src/python/serials_find.py
Labels: V3.0 :rocket:

#1708 Fix log level on RF mode cycling
  src/src/rx_main.cpp
Labels: bug :bug:, V3.0 :rocket:

#1712 Include unchecked checkboxes in options submit
  src/html/scan.js
Labels: bug :bug:, V3.0 :rocket:

#1710 Add missing entries to mDNS
  src/lib/WIFI/devWIFI.cpp
Labels: bug :bug:, V3.0 :rocket:

#1716 Incorrect board_config for HGLRC Hermes 2400 TX
  src/hardware/TX/HGLRC Hermes 2400.json
  src/hardware/targets.json
Labels: bug :bug:, V3.0 :rocket:

#1724 Adjust PWMPEX vbat_scale with testing results
  src/hardware/RX/Generic 2400 PWMP6.json
  src/hardware/RX/Generic 2400 PWMP7.json
Labels: V3.0 :rocket:
