Repository ExpressLRS/ExpressLRS, pull requests merged in 2022-08, with the labels that each got.

#1739 Fix BETAFPV Nano `prior_target_name`
  src/hardware/targets.json
Labels: bug :bug:, V3.0 :rocket:

#1738 TX12 Alias Target
  src/hardware/targets.json
Labels: V3.0 :rocket:

#1734 Only change RF power when idle, delay disconnected
  src/lib/DAC/DAC.cpp
  src/lib/DAC/DAC.h
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/SX127xDriver/SX127x.h
  src/lib/SX1280Driver/SX1280.cpp
  src/lib/SX1280Driver/SX1280.h
  src/lib/SX1280Driver/SX1280_Regs.h
  src/src/tx_main.cpp
Labels: bug :bug:, V3.0 :rocket:

#1737 Fix 1:2 telem ratio on ESP32 RX
  src/lib/HWTIMER/ESP32_hwTimer.cpp
Labels: bug :bug:, V3.0 :rocket:

#1743 Only adjust PFD when a new result is available
  src/lib/PFD/PFD.h
  src/src/rx_main.cpp
Labels: bug :bug:, V3.0 :rocket:

#1750 Fix BLE/WiFi exit on LUA
  src/lib/LUA/tx_devLUA.cpp
Labels: bug :bug:, V3.0 :rocket:

#1744 Delay sending of VTX Admin if reconnected quickly
  src/lib/VTX/devVTX.cpp
Labels: bug :bug:, V3.0 :rocket:

#1752 Move HandleUARTIn to devCRSF timeout function
  src/lib/CRSF/devCRSF_rx.cpp
  src/src/rx_main.cpp
Labels: bug :bug:, V3.0 :rocket:

#1730 Fixing unit tests
  src/lib/CRSF/devCRSF.h
  src/lib/CRSF/devCRSF_tx.cpp
  src/lib/OPTIONS/options.h
Labels: bug :bug:, V3.1 :thinking:

#1758 Dont sent eeprom write when using pitmode on a switch
  src/lib/VTX/devVTX.cpp
Labels: V3.0 :rocket:

#1753 Fix popup touch events, remove from B&W
  src/lua/elrsV3.lua
Labels: V3.0 :rocket:

#1774 Fix "Unknown LUA 16" message being logged spuriously!
  src/lib/CRSF/CRSF.cpp
Labels: bug :bug:, V3.1 :thinking:

#1776 Pin define `ant_ctrl` typo on Namimno 2.4g Diversity target
  src/hardware/RX/Namimno FLASH 2400 PA.json
Labels: bug :bug:, V3.0 :rocket:

#1786 Fix spelling errors in the web UI
  src/html/index.html
  src/html/scan.js
Labels: bug :bug:, V3.0 :rocket:

#1780 Avoid updating the thermal device if no change
  src/lib/THERMAL/thermal.cpp
Labels: V3.0 :rocket:

#1796 Foxeer RX target
  src/hardware/RX/Generic 2400 PA RGB.json
  src/hardware/targets.json
  src/targets/diy_2400.ini
  src/targets/foxeer_2400.ini
Labels: V3.0 :rocket:

#1795 Fullres power level reports 0mW for 50mW
  src/lib/CRSF/devCRSF_tx.cpp
  src/lib/OTA/OTA.cpp
  src/lib/OTA/OTA.h
  src/lib/POWERMGNT/POWERMGNT.cpp
  src/lib/POWERMGNT/POWERMGNT.h
  src/test/test_ota/test_switches.cpp
Labels: bug :bug:, V3.0 :rocket:

#1798 Fix wifi auto on interval when not entered/selected in configurator
  src/lib/OPTIONS/options.cpp
Labels: bug :bug:, V3.0 :rocket:

#1765 Remove usage of IsArmed from receivers
  src/lib/BUTTON/button.h
  src/lib/BUTTON/devButton.cpp
  src/lib/CRSF/CRSF.h
  src/lib/VTXSPI/devVTXSPI.cpp
  src/lib/VTXSPI/devVTXSPI.h
Labels: V3.1 :thinking:
