Repository ExpressLRS/ExpressLRS, pull requests merged in 2022-10, with the labels that each got.

#1871 Hide the "unlock higher power" option
  src/html/index.html
  src/html/scan.js
  src/lib/WIFI/devWIFI.cpp
Labels: bug :bug:, V3.1 :thinking:

#1872 Fix HappyModel Dual using wrong target file
  src/hardware/targets.json
Labels: bug :bug:, V3.1 :thinking:

#1863 Fix for RX not showing UID and other options
  src/html/scan.js
Labels: bug :bug:, V3.1 :thinking:

#1757 Allow config of RX initial packet rate
  src/include/common.h
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/LUA/lua.cpp
  src/lib/LUA/lua.h
  src/lib/LUA/rx_devLUA.cpp
  src/lib/LUA/rxtx_devLua.cpp
  src/lib/LUA/rxtx_devLua.h
  src/lib/LUA/tx_devLUA.cpp
  src/src/common.cpp
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: V3.1 :thinking:

#1876 add uplink_RSSI_2 to true diversity rx
  src/lib/SX127xDriver/SX127x.h
  src/lib/SX1280Driver/SX1280.cpp
  src/lib/SX1280Driver/SX1280.h
  src/lib/SX1280Driver/SX1280_Regs.h
  src/lib/SX1280Driver/SX1280_hal.cpp
  src/lib/SX1280Driver/SX1280_hal.h
  src/lib/SX12xxDriverCommon/SX12xxDriverCommon.h
  src/lib/WIFI/devWIFI.cpp
  src/src/rx_main.cpp
Labels: V3.1 :thinking:

#1763 Add PWM mapping/failsafe to RX Lua
  src/lib/CONFIG/config.h
  src/lib/CRSF/CRSF.h
  src/lib/LUA/rx_devLUA.cpp
Labels: V3.1 :thinking:

#1841 Radio GPIO optimisation
  src/lib/SX1280Driver/SX1280.cpp
  src/lib/SX1280Driver/SX1280_hal.cpp
  src/lib/SX1280Driver/SX1280_hal.h
  src/targets/common.ini
  src/targets/unified.ini
Labels: bugfixes :lady_beetle:, V3.1 :thinking:

#1845 [3.0.1] Radio GPIO optimisation
  src/lib/SX1280Driver/SX1280.cpp
  src/lib/SX1280Driver/SX1280_hal.cpp
  src/lib/SX1280Driver/SX1280_hal.h
  src/targets/unified.ini
Labels: V3.0 :rocket:

#1867 Faster OTX sync recovery and stability
  src/lib/CRSF/CRSF.cpp
  src/lib/CRSF/CRSF.h
  src/user_defines.txt
Labels: V3.1 :thinking:

#1879 3.x merge to master
  src/lib/WIFI/devWIFI.cpp
  src/platformio.ini
Labels: DO NOT SQUASH MERGE

#1886 [3.0.1] Fix Foxeer target locator name
  src/targets/foxeer_2400.ini
Labels: bug :bug:, V3.0 :rocket:

#1881 Fix wifi led when in binding mode
  src/lib/WIFI/devWIFI.cpp
Labels: bugfixes :lady_beetle:, V3.1 :thinking:

#1882 Disable TX diversity on FM30
  src/include/target/FM30_TX.h
  src/src/tx_main.cpp
Labels: bug :bug:, V3.0 :rocket:

#1874 Move uart writes from ISR on STM32
  src/lib/CRSF/devCRSF_rx.cpp
Labels: V3.0 :rocket:, bugfixes :lady_beetle:

#1889 Lowering upload speed
  src/python/build_env_setup.py
Labels: V3.1 :thinking:

#1896 Add EMAX nano TX targets
  src/hardware/TX/EMAX 2400 Nano.json
  src/hardware/TX/EMAX 900 Nano.json
  src/hardware/targets.json
  src/targets/emax_2400.ini
  src/targets/emax_900.ini
Labels: new target :dart:, V3.1 :thinking:

#1901 Fix power on boot being default power
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/SX1280Driver/SX1280.cpp
Labels: bugfixes :lady_beetle:, V3.1 :thinking:

#1897 Set BLE to max power
  src/lib/BLE/devBLE.cpp
Labels: enhancement :magic_wand:, V3.1 :thinking:

#1892 Add native barometer support
  src/hardware/RX/Vario 2400.json
  src/hardware/targets.json
  src/html/hardware.html
  src/lib/AnalogVbat/devAnalogVbat.cpp
  src/lib/AnalogVbat/devAnalogVbat.h
  src/lib/Baro/baro_base.cpp
  src/lib/Baro/baro_base.h
  src/lib/Baro/baro_spl06.cpp
  src/lib/Baro/baro_spl06.h
  src/lib/Baro/baro_spl06_regs.h
  src/lib/Baro/devBaro.cpp
  src/lib/Baro/devBaro.h
  src/lib/CrsfProtocol/crsf_protocol.h
  src/lib/ServoOutput/ServoMgr.cpp
  src/lib/ServoOutput/devServoOutput.cpp
  src/src/rx_main.cpp
  src/targets/diy_2400.ini
Labels: enhancement :magic_wand:, V3.1 :thinking:

#1888 Target validation during github build
  .github/workflows/build.yml
  src/hardware/targets.json
  src/python/targets_validator.py
Labels: V3.1 :thinking:

#1870 LBT bug fixes and telemetry lost/recovered solution
  src/hardware/RX/Generic 2400 Diversity PA.json
  src/hardware/RX/Generic 2400 PA RGB.json
  src/hardware/RX/Generic 2400 PA.json
  src/hardware/RX/Generic 2400 True Diversity PA and VTx.json
  src/hardware/RX/Generic 2400 True Diversity PA.json
  src/hardware/RX/Namimno FLASH 2400 PA.json
  src/hardware/RX/iFlight 2400.json
  src/hardware/TX/AXIS Thor 2400.json
  src/hardware/TX/BETAFPV 2400 LiteRadio 3.json
  src/hardware/TX/BETAFPV 2400 Micro 1W.json
  src/hardware/TX/BETAFPV 2400 Micro.json
  src/hardware/TX/BETAFPV 2400 Nano.json
  src/hardware/TX/DIY 2400 DupleTX ESP.json
  src/hardware/TX/DIY 2400 DupleTX.json
  src/hardware/TX/DIY 2400 E28.json
  src/hardware/TX/DIY 2400 F27.json
  src/hardware/TX/DIY 2400 Mini.json
  src/hardware/TX/EMAX 2400 OLED.json
  src/hardware/TX/HGLRC Hermes 2400.json
  src/hardware/TX/HappyModel ES24 Pro.json
  src/hardware/TX/HappyModel ES24.json
  src/hardware/TX/Jumper AION Nano.json
  src/hardware/TX/Jumper T-Lite.json
  src/hardware/TX/Jumper T-Pro.json
  src/hardware/TX/Namimno Flash OLED.json
  src/hardware/TX/QuadKopters JR 2400.json
  src/hardware/TX/Radiomaster TX16S 2400.json
  src/hardware/TX/Radiomaster Zorro.json
  src/hardware/TX/Vantac Lite.json
  src/hardware/TX/iFlight 2400.json
  src/include/hardware.h
  src/include/target/Unified_ESP32_TX.h
  src/include/target/Unified_ESP8285_TX.h
  src/include/target/Unified_ESP_RX.h
  src/lib/LBT/LBT.cpp
  src/lib/LBT/LBT.h
  src/lib/OPTIONS/hardware.cpp
  src/lib/SX1280Driver/SX1280.cpp
  src/lib/SX1280Driver/SX1280.h
  src/lib/SX1280Driver/SX1280_Regs.h
  src/src/dynpower.cpp
  src/src/rx_main.cpp
Labels: bugfixes :lady_beetle:, V3.1 :thinking:

#1911 Remove binary file so it's built each time
  src/python/build_env_setup.py
Labels: bugfixes :lady_beetle:, V3.1 :thinking:

#1922 Fix QuadKoptersNano 2400 RX referencing Generic 900 target
  src/targets/quadkopters_2400.ini
Labels: bug :bug:, V3.0 :rocket:

#1913 The FIFO's actions need to be atomic
  src/lib/FIFO/FIFO.cpp
  src/lib/FIFO/FIFO.h
  src/lib/FIFO_GENERIC/FIFO_GENERIC.h
Labels: V3.1 :thinking:
