Repository ExpressLRS/ExpressLRS, pull requests merged in 2022-12, with the labels that each got.

#1975 LNA + RGB Receivers via BFPassthrough Failing due to missing env scripts
  src/targets/diy_2400.ini
  src/targets/foxeer_2400.ini
  src/targets/unified.ini
Labels: V3.1 :thinking:

#1974 Move pwm rx MappingFolder
  src/lib/LUA/rx_devLUA.cpp
Labels: V3.1 :thinking:

#1980 Telemetry fix
  src/lib/Telemetry/telemetry.cpp
  src/test/test_telemetry/test_telemetry.cpp
Labels: V3.1 :thinking:

#1976 Config Fixes
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config_legacy.h
  src/src/rx_main.cpp
Labels: V3.1 :thinking:

#1978 correct antenna diversity lua labels
  src/lib/LUA/rx_devLUA.cpp
Labels: V3.1 :thinking:

#1981 Correct 900 rx power settings
  src/hardware/RX/Generic 900 PWMP.json
  src/hardware/RX/Generic 900.json
  src/hardware/RX/Namimno VOYAGER 900.json
Labels: V3.1 :thinking:

#1983 Merge 3.x.x to master
  src/hardware/RX/Generic 900 PWMP.json
  src/hardware/RX/Generic 900.json
  src/hardware/RX/Namimno VOYAGER 900.json
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/CONFIG/config_legacy.h
  src/lib/CRSF/devCRSF_rx.cpp
  src/lib/LUA/rx_devLUA.cpp
  src/lib/OTA/OTA.h
  src/lib/Telemetry/telemetry.cpp
  src/src/rx_main.cpp
  src/targets/common.ini
  src/targets/diy_2400.ini
  src/targets/foxeer_2400.ini
  src/targets/unified.ini
  src/test/test_telemetry/test_telemetry.cpp
Labels: DO NOT SQUASH MERGE

#1998 Potential fix for PWM reboot
  src/lib/CRSF/CRSF.cpp
  src/lib/CRSF/CRSF.h
Labels: V3.1 :thinking:

#1943 Module Configuration Import/Export
  src/html/index.html
  src/html/scan.js
  src/lib/CONFIG/config.h
  src/lib/WIFI/devWIFI.cpp
  src/python/serve_html.py
Labels: V3.2 :beer:

#1990 don't stuck in WatiOnBusy(sx1280)
  src/lib/SX1280Driver/SX1280_hal.cpp
Labels: V3.2 :beer:

#1999 Add Radiomaster Boxer internal module
  src/hardware/TX/Radiomaster Boxer.json
  src/hardware/targets.json
  src/targets/radiomaster_2400.ini
Labels: V3.2 :beer:

#1986 make EMAX 900 OLED Better power performance
  src/hardware/TX/EMAX 900 OLED.json
Labels: V3.2 :beer:

#1948 Fix github build warnings
  .github/workflows/build.yml
Labels: V3.2 :beer:

#1985 Add a true-diversity (non-PA) + VTx receiver
  src/hardware/RX/Generic 2400 True Diversity and VTx.json
  src/hardware/targets.json
Labels: V3.2 :beer:

#2019 Build and flash gzipped binary on ESP8285
  src/python/build_env_setup.py
  src/python/esp_compress.py
  src/python/upload_via_esp8266_backpack.py
Labels: bugfixes :lady_beetle:, V3.2 :beer:

#1997 Dont reset FreqCorrection on LostConnection
  src/src/rx_main.cpp
Labels: V3.2 :beer:

#2020 Failsafe channel mapping to reflect the proper input channel
  src/lib/LUA/rx_devLUA.cpp
Labels: bugfixes :lady_beetle:, V3.2 :beer:

#2011 Configurable PWM fan speeds
  src/hardware/TX/Radiomaster Boxer.json
  src/hardware/TX/Radiomaster Ranger.json
  src/html/hardware.html
  src/include/hardware.h
  src/include/target/Unified_ESP32_TX.h
  src/lib/OPTIONS/hardware.cpp
  src/lib/THERMAL/devThermal.cpp
Labels: V3.2 :beer:

#2024 Only do compression for wifi
  src/python/build_env_setup.py
Labels: V3.2 :beer:

#1951 Fix errors on PWM output
  src/lib/ServoOutput/ServoMgr.cpp
  src/lib/ServoOutput/ServoMgr.h
Labels: V3.2 :beer:

#2006 Merge 3.x.x to master
  src/lib/CRSF/CRSF.cpp
  src/lib/CRSF/CRSF.h
  src/lib/LUA/rx_devLUA.cpp
Labels: DO NOT SQUASH MERGE, V3.2 :beer:
