Repository ExpressLRS/ExpressLRS, pull requests merged in 2022-05, with the labels that each got.

#1550 Add BETAFPV literadio3 target
  src/include/target/BETAFPV_2400_TX_LITERADIO3.h
  src/targets/betafpv_2400.ini
Labels: new target

#1435 Variable autobaud
  src/lib/CRSF/CRSF.cpp
  src/lib/CRSF/CRSF.h
Labels: V3.0

#1557 Switch Jumper TPro GPIO_PIN_DEBUG pins... mod for TPro Backpack
  src/include/target/Jumper_AION_2400_T-Pro_TX.h
Labels: V3.0

#1570 Fix RX WiFi AP mDNS not working
  src/lib/WIFI/devWIFI.cpp
Labels: V3.0

#1575 Fix PIO warnings and rename test directories so they work!
  src/platformio.ini
  src/targets/HGLRC_2400.ini
  src/targets/Jumper_2400.ini
  src/targets/MATEK_2400.ini
  src/targets/axis_2400.ini
  src/targets/betafpv_2400.ini
  src/targets/betafpv_900.ini
  src/targets/common.ini
  src/targets/diy_2400.ini
  src/targets/diy_900.ini
  src/targets/diy_ble_joystick.ini
  src/targets/frsky.ini
  src/targets/happymodel_2400.ini
  src/targets/happymodel_900.ini
  src/targets/iFlight_2400.ini
  src/targets/iFlight_900.ini
  src/targets/imrc.ini
  src/targets/namimnorc_2400.ini
  src/targets/namimnorc_900.ini
  src/targets/quadkopters_2400.ini
  src/targets/radiomaster_2400.ini
  src/targets/siyi.ini
  src/targets/vantac_2400.ini
  src/test/test_crc/test_crc.cpp
  src/test/test_crc/ucrc_t.cpp
  src/test/test_crc/ucrc_t.h
  src/test/test_crsf/test_crsf.cpp
  src/test/test_fhss/test_fhss.cpp
  src/test/test_fifo/test_fifo.cpp
  src/test/test_fmap/test_fmap.cpp
  src/test/test_msp/encapsulated_msp_tests.cpp
  src/test/test_msp/mock_serial.h
  src/test/test_msp/msp_tests.cpp
  src/test/test_msp2crsf2msp/test_msp2crsf2msp.cpp
  src/test/test_ota/test_switches.cpp
  src/test/test_stubborn/test_stubborn.cpp
  src/test/test_telemetry/test_telemetry.cpp
Labels: V3.0

#1554 Allow backpack passthrough on s-port connected TX modules
  src/lib/Backpack/devBackpack.cpp
Labels: V3.0

#1578 Fix for traditional bind mode
  src/src/rx_main.cpp
Labels: V3.0

#1581 Restore HTTP upload functionality
  src/python/upload_via_esp8266_backpack.py
Labels: V3.0

#1596 Vantac RX has a special hardware, not Generic
  src/hardware/targets.json
Labels: V3.0

#1558 Refactor servo output to device, add per-servo output rate
  src/hardware/RX/Generic 2400 PWMP6.json
  src/hardware/RX/Generic 2400 PWMP7.json
  src/html/main.css
  src/html/rx_index.html
  src/html/scan.js
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/ServoOutput/ServoMgr_8266.cpp
  src/lib/ServoOutput/ServoMgr_8266.h
  src/lib/ServoOutput/devServoOutput.cpp
  src/lib/ServoOutput/devServoOutput.h
  src/lib/ServoOutput/waveform_8266.cpp
  src/lib/ServoOutput/waveform_8266.h
  src/lib/WIFI/devWIFI.cpp
  src/src/rx_main.cpp
  src/targets/diy_2400.ini
Labels: needs doc, V3.0

#1601 Fix wifi force flash
  src/lib/WIFI/devWIFI.cpp
Labels: V3.0

#1602 Fix the font overflowing on TFT screens
  src/lib/SCREEN/TFT/Pragma_Sans37pt7b.h
  src/lib/SCREEN/TFT/Pragma_Sans38pt7b.h
  src/lib/SCREEN/TFT/tftdisplay.cpp
Labels: V3.0
