Repository ExpressLRS/ExpressLRS, pull requests merged in 2022-09, with the labels that each got.

#1764 Fix 8285 RX as TX
  src/hardware/targets.json
  src/lib/CRSF/devCRSF_tx.cpp
Labels: bug :bug:, V3.1 :thinking:

#1775 Add delay after CRSFconnect before TX transmit starts
  src/include/common.h
  src/lib/CONFIG/config.cpp
  src/src/tx_main.cpp
Labels: bug :bug:, V3.0 :rocket:

#1808 Return sensitivity to the Packet Rate item
  src/lib/LUA/tx_devLUA.cpp
Labels: bug :bug:, V3.0 :rocket:

#1770 Fixes TFT quirk displaying overwritten text
  src/lib/SCREEN/TFT/tftdisplay.cpp
  src/lib/SCREEN/display.h
  src/lib/SCREEN/menu.cpp
Labels: V3.1 :thinking:

#1809 Don't pause Lua loading when in edit mode
  src/lua/elrsV3.lua
Labels: V3.0 :rocket:

#1792 Allow changing switch mode when connected
  src/src/rx_main.cpp
Labels: V3.0 :rocket:

#1815 Use 250hz default rate for 2.4, 50hz for 868/900
  src/lib/CONFIG/config.cpp
Labels: bug :bug:, V3.0 :rocket:

#1821 Add Happymodel EP1 Dual target
  src/hardware/targets.json
  src/targets/happymodel_2400.ini
Labels: V3.0 :rocket:

#1822 Power level 0 is malfunctioning on Team900 HWs
  src/lib/SX127xDriver/SX127x.h
  src/lib/SX127xDriver/SX127xRegs.h
Labels: V3.0 :rocket:, bugfixes

#1823 Fixes configurator passed Lua name not getting into Unified firmware
  src/python/UnifiedConfiguration.py
  src/python/build_flags.py
Labels: bug :bug:, V3.0 :rocket:

#1666 900Mhz ESP32 RX
  src/include/target/Unified_ESP_RX.h
  src/targets/unified.ini
Labels: V3.1 :thinking:

#1827 Fix ESP32 RX being labelled as TX in MDNS
  src/lib/WIFI/devWIFI.cpp
Labels: bug :bug:, V3.1 :thinking:

#1785 Continuous wave test mode
  src/html/cw.html
  src/html/cw.js
  src/lib/POWERMGNT/POWERMGNT.cpp
  src/lib/SX1280Driver/SX1280.cpp
  src/lib/SX1280Driver/SX1280.h
  src/lib/WIFI/devWIFI.cpp
  src/python/build_html.py
Labels: V3.1 :thinking:

#1842 [3.0.1] Add foxeer to the main ini file!
  src/platformio.ini
Labels: bug :bug:, V3.0 :rocket:

#1729 Powersave/g-sensor for OLED devices
  src/lib/SCREEN/OLED/XBMStrings.h
  src/lib/SCREEN/OLED/oleddisplay.cpp
Labels: V3.1 :thinking:

#1831 Platform lib upgrade
  .github/workflows/build.yml
  src/lib/BLE/devBLE.cpp
  src/lib/CRSF/CRSF.cpp
  src/lib/VTXSPI/devVTXSPI.cpp
  src/lib/WIFI/devWIFI.cpp
  src/targets/common.ini
Labels: V3.1 :thinking:

#1830 Put "important" tasks on core 1 (loop core)
  src/lib/Backpack/devBackpack.cpp
  src/lib/Backpack/devBackpack.h
  src/src/tx_main.cpp
Labels: V3.1 :thinking:

#1761 User configurable TX button actions
  src/html/hardware.html
  src/html/index.html
  src/html/scan.js
  src/include/common.h
  src/include/hardware.h
  src/include/target/Unified_ESP32_TX.h
  src/include/target/Unified_ESP8285_TX.h
  src/lib/BUTTON/button.h
  src/lib/BUTTON/devButton.cpp
  src/lib/BUTTON/devButton.h
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/GSENSOR/devGsensor.cpp
  src/lib/OPTIONS/hardware.cpp
  src/lib/SCREEN/OLED/oleddisplay.cpp
  src/lib/SCREEN/TFT/tftdisplay.cpp
  src/lib/SCREEN/devScreen.cpp
  src/lib/SCREEN/menu.h
  src/lib/VTX/devVTX.cpp
  src/lib/WIFI/devWIFI.cpp
  src/python/build_html.py
  src/python/external/bottle.py
  src/python/serve_html.py
  src/src/dynpower.cpp
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: V3.1 :thinking:

#1837 User configurable RGB LED colors for user buttons
  src/html/hardware.html
  src/html/index.html
  src/html/scan.js
  src/include/hardware.h
  src/include/target/Unified_ESP32_TX.h
  src/include/target/Unified_ESP8285_TX.h
  src/lib/BUTTON/devButton.cpp
  src/lib/CONFIG/config.cpp
  src/lib/CRSF/devCRSF_tx.cpp
  src/lib/LED/devRGB.cpp
  src/lib/OPTIONS/hardware.cpp
  src/lib/WIFI/devWIFI.cpp
  src/python/serve_html.py
  src/targets/unified.ini
Labels: V3.1 :thinking:

#1760 PWM fan support
  src/html/hardware.html
  src/include/hardware.h
  src/include/target/Unified_ESP32_TX.h
  src/include/targets.h
  src/lib/LUA/tx_devLUA.cpp
  src/lib/OPTIONS/hardware.cpp
  src/lib/POWERMGNT/POWERMGNT.cpp
  src/lib/THERMAL/devThermal.cpp
  src/lib/THERMAL/rpm.cpp
Labels: V3.1 :thinking:

#1748 Renamed full diversity rx json configs to be more descriptive
  src/hardware/RX/Generic 2400 Diversity PA.json
  src/hardware/RX/Generic 2400 True Diversity PA and VTx.json
  src/hardware/RX/Generic 2400 True Diversity PA.json
  src/hardware/targets.json
Labels: V3.1 :thinking:

#1859 update mismatch firmware warning
  src/lib/WIFI/devWIFI.cpp
Labels: V3.0 :rocket:
