Repository ExpressLRS/ExpressLRS, pull requests merged in 2023-03, with the labels that each got.

#2067 Added foxeer 900M target
  src/hardware/targets.json
Labels: new target :dart:, V3.3 🍕

#1968 Only use serial crsf battery sensor if detected
  src/lib/AnalogVbat/devAnalogVbat.cpp
  src/lib/Telemetry/telemetry.cpp
  src/lib/Telemetry/telemetry.h
Labels: V3.3 🍕

#1982 sx127xHal update
  src/html/hardware.html
  src/include/hardware.h
  src/include/target/Unified_ESP32_TX.h
  src/include/target/Unified_ESP8285_TX.h
  src/include/target/Unified_ESP_RX.h
  src/include/targets.h
  src/lib/OPTIONS/hardware.cpp
  src/lib/RFAMP/RFAMP_hal.cpp
  src/lib/RFAMP/RFAMP_hal.h
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/SX127xDriver/SX127xHal.cpp
  src/lib/SX127xDriver/SX127xHal.h
  src/lib/SX127xDriver/SX127xRegs.h
  src/lib/SX1280Driver/SX1280.cpp
  src/lib/SX1280Driver/SX1280_hal.cpp
  src/lib/SX1280Driver/SX1280_hal.h
Labels: V3.3 🍕

#2041 Add backpack command to request version
  src/lib/Backpack/devBackpack.cpp
  src/lib/LUA/tx_devLUA.cpp
  src/lib/MSP/msp.cpp
  src/lib/MSP/msp.h
  src/lib/MSP/msptypes.h
  src/src/tx_main.cpp
Labels: V3.3 🍕

#2054 Add config option to disable TX backpack
  src/lib/Backpack/devBackpack.cpp
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/LUA/tx_devLUA.cpp
Labels: V3.3 🍕

#2021 Idle core0 on esp32 platform
  src/include/rxtx_common.h
  src/lib/WIFI/devWIFI.cpp
  src/src/rx_main.cpp
  src/src/rxtx_common.cpp
  src/src/tx_main.cpp
Labels: V3.3 🍕

#2080 Reduce RAM use of Options/Hardware loading
  src/lib/OPTIONS/EspFlashStream.cpp
  src/lib/OPTIONS/EspFlashStream.h
  src/lib/OPTIONS/hardware.cpp
  src/lib/OPTIONS/options.cpp
  src/lib/OPTIONS/options.h
Labels: V3.3 🍕

#1993 Gemini/Diversity 900
  src/hardware/RX/Generic 900 True Diversity PA.json
  src/hardware/TX/Generic 900 Gemini.json
  src/hardware/targets.json
  src/lib/CONFIG/config.cpp
  src/lib/FHSS/FHSS.cpp
  src/lib/FHSS/FHSS.h
  src/lib/RFAMP/RFAMP_hal.cpp
  src/lib/RFAMP/RFAMP_hal.h
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/SX127xDriver/SX127x.h
  src/lib/SX127xDriver/SX127xHal.cpp
  src/lib/SX127xDriver/SX127xHal.h
  src/lib/SX127xDriver/SX127xRegs.h
  src/src/rx_main.cpp
Labels: V3.3 🍕

#2062 Fix rx_main::MspReceiveComplete()
  src/src/rx_main.cpp
Labels: bugfixes :lady_beetle:, V3.2 :beer:

#2103 Fix race condition in Telemetry
  src/lib/Telemetry/telemetry.cpp
Labels: bugfixes :lady_beetle:, V3.2 :beer:

#2107 Fix binary configurator for targets with `-`
  src/python/binary_configurator.py
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2050 Update BLE Joystick
  src/lib/BLE/devBLE.cpp
  src/targets/common.ini
Labels: V3.3 🍕

#2089 D modes for Team900
  src/include/common.h
  src/lib/LUA/rxtx_devLua.cpp
  src/lib/SCREEN/display.cpp
  src/src/common.cpp
Labels: For Discussion :mega:, V3.3 🍕, V4.0

#2112 Put the correct UID (the one being used) into the json response
  src/lib/WIFI/devWIFI.cpp
Labels: bugfixes :lady_beetle:, V3.2 :beer:

#2106 Fixes loop throttle & no-layout wifi mode
  src/include/rxtx_common.h
  src/lib/DEVICE/device.cpp
  src/lib/DEVICE/device.h
  src/lib/LUA/rx_devLUA.cpp
  src/lib/WIFI/devWIFI.cpp
  src/src/rx_main.cpp
  src/src/rxtx_common.cpp
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2094 RX serial refactor (user selectable CRSF/SBUS serial protocol)
  src/html/index.html
  src/html/scan.js
  src/include/common.h
  src/include/targets.h
  src/lib/BLE/devBLE.cpp
  src/lib/Backpack/devBackpack.cpp
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/CONFIG/config_legacy.h
  src/lib/CRSF/CRSF.cpp
  src/lib/CRSF/CRSF.h
  src/lib/CRSF/devCRSF.h
  src/lib/CRSF/devCRSF_rx.cpp
  src/lib/CRSF2MSP/crsf2msp.h
  src/lib/CRSF2MSP/msp2crsf.h
  src/lib/CrsfProtocol/crsf_protocol.h
  src/lib/FIFO/FIFO.h
  src/lib/LUA/lua.cpp
  src/lib/LUA/lua.h
  src/lib/LUA/rx_devLUA.cpp
  src/lib/OPTIONS/options.cpp
  src/lib/OPTIONS/options.h
  src/lib/OTA/OTA.cpp
  src/lib/OTA/OTA.h
  src/lib/ServoOutput/ServoMgr.h
  src/lib/ServoOutput/devServoOutput.cpp
  src/lib/Telemetry/telemetry.cpp
  src/lib/VTX/devVTX.cpp
  src/lib/WIFI/devWIFI.cpp
  src/python/binary_configurator.py
  src/python/build_flags.py
  src/python/serve_html.py
  src/src/common.cpp
  src/src/dynpower.cpp
  src/src/rx-serial/SerialAirPort.cpp
  src/src/rx-serial/SerialAirPort.h
  src/src/rx-serial/SerialCRSF.cpp
  src/src/rx-serial/SerialCRSF.h
  src/src/rx-serial/SerialIO.cpp
  src/src/rx-serial/SerialIO.h
  src/src/rx-serial/SerialNOOP.h
  src/src/rx-serial/SerialSBUS.cpp
  src/src/rx-serial/SerialSBUS.h
  src/src/rx-serial/devSerialIO.cpp
  src/src/rx-serial/devSerialIO.h
  src/src/rx_main.cpp
  src/src/tx_main.cpp
  src/test/test_crsf/test_crsf.cpp
  src/test/test_fifo/test_fifo.cpp
  src/test/test_msp/encapsulated_msp_tests.cpp
  src/test/test_msp/msp_tests.cpp
  src/test/test_ota/test_switches.cpp
  src/test/test_telemetry/test_telemetry.cpp
  src/user_defines.txt
Labels: V3.3 🍕

#2115 Fix RX Lua after PR#2062
  src/src/rx_main.cpp
Labels: bugfixes :lady_beetle:, V3.2 :beer:

#2118 Fix overflow on F1000 TLM 1:2
  src/lib/LUA/tx_devLUA.cpp
Labels: bugfixes :lady_beetle:, V3.2 :beer:

#2117 Fix OLED change packet rate
  src/lib/SCREEN/menu.cpp
Labels: bugfixes :lady_beetle:, V3.2 :beer:

#2123 Added missing DEBUG_CRSF_NO_OUTPUT
  src/include/targets.h
  src/src/rx-serial/SerialCRSF.cpp
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2126 Emax
  src/hardware/TX/EMAX 900 Nano.json
  src/hardware/TX/EMAX 900 OLED.json
Labels: V3.2 :beer:

#2138 Setting self.source_lineno within range 0-22 (#2116)
  src/python/external/wheezy/template/engine.py
Labels: V3.2 :beer:

#1973 Add AnyLeaf targets
  src/hardware/targets.json
Labels: V3.3 🍕

#2142 Power detection fix for TX modules with SKY85321
  src/lib/POWERMGNT/POWERMGNT.cpp
  src/lib/POWERMGNT/POWERMGNT.h
  src/lib/POWER_DETECT/devPDET.cpp
Labels: bugfixes :lady_beetle:, V3.2 :beer:
