Repository ExpressLRS/ExpressLRS, pull requests merged in 2023-08, with the labels that each got.

#2324 disable msp vtx after no comms on boot
  src/lib/MSPVTX/devMSPVTX.cpp
  src/lib/VTXSPI/devVTXSPI.cpp
Labels: enhancement :magic_wand:, V3.4 🍟

#2316 Allow SPI VTx operation without FC
  src/src/rx_main.cpp
Labels: enhancement :magic_wand:, V3.4 🍟

#2342 Add Radiomaster Pocket alias
  src/hardware/targets.json
Labels: new target :dart:, V3.3 🍕

#2351 add prior_target_name to Jumper T-20
  src/hardware/targets.json
Labels: V3.3 🍕

#2335 Correct sx1280 irqMask and dio1Mask data type
  src/lib/SX1280Driver/SX1280.cpp
Labels: V3.3 🍕

#2334 Correct rx power when using Regulatory_Domain_EU_CE_2400
  src/lib/POWERMGNT/POWERMGNT.h
  src/lib/SCREEN/menu.cpp
Labels: V3.3 🍕

#2354 Add Back Stock BL to other STM targets
  src/hardware/targets.json
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2359 Happymodel 900 TX not able to select 1W
  src/hardware/TX/HappyModel ES900.json
  src/hardware/targets.json
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2356 Document the device API
  src/lib/DEVICE/device.cpp
  src/lib/DEVICE/device.h
Labels: V3.4 🍟, house keeping :broom:

#2365 Support 16 channel CRSF
  src/src/rx-serial/SerialCRSF.cpp
Labels: enhancement :magic_wand:, V3.4 🍟

#2320 Cleanup of the CRSF header and code
  src/lib/CRSF/CRSF.cpp
  src/lib/CRSF/CRSF.h
  src/lib/CrsfProtocol/crsf_protocol.h
Labels: V3.4 🍟, house keeping :broom:

#2364 FIFO cleanup and documentation
  src/include/rxtx_common.h
  src/lib/CRSF/CRSF.cpp
  src/lib/CRSF2MSP/crsf2msp.cpp
  src/lib/CRSF2MSP/crsf2msp.h
  src/lib/CRSF2MSP/msp2crsf.cpp
  src/lib/CRSF2MSP/msp2crsf.h
  src/lib/FIFO/FIFO.cpp
  src/lib/FIFO/FIFO.h
  src/lib/FIFO_GENERIC/FIFO_GENERIC.h
  src/lib/OTA/OTA.cpp
  src/lib/OTA/OTA.h
  src/lib/TCPSOCKET/tcpsocket.cpp
  src/lib/TCPSOCKET/tcpsocket.h
  src/src/rx-serial/SerialAirPort.cpp
  src/src/rx-serial/SerialAirPort.h
  src/src/rx-serial/SerialCRSF.cpp
  src/src/rx-serial/SerialIO.cpp
  src/src/rx-serial/SerialIO.h
  src/src/rx-serial/SerialNOOP.h
  src/src/tx_main.cpp
  src/test/test_fifo/test_fifo.cpp
Labels: V3.4 🍟, house keeping :broom:

#2321 Call static things in a static way!
  src/lib/LUA/lua.cpp
  src/lib/VTX/devVTX.cpp
  src/src/rx_main.cpp
  src/src/tx_main.cpp
  src/test/test_crsf/test_crsf.cpp
  src/test/test_msp/encapsulated_msp_tests.cpp
  src/test/test_ota/test_switches.cpp
Labels: V3.4 🍟, house keeping :broom:
