Repository ExpressLRS/ExpressLRS, pull requests merged in 2023-06, with the labels that each got.

#2236 Add BETAFPV Super-D 900 target
  src/hardware/targets.json
Labels: V3.3 🍕

#2238 Binary artifact archive updates
  .github/workflows/build.yml
  src/python/binary_configurator.py
  src/python/binary_flash.py
Labels: V3.3 🍕

#2239 Fix Siyi RX cloudbuild flashing
  src/hardware/targets.json
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2245 Remove extra ESP32 binaries when doing "Build" mode
  src/python/binary_flash.py
Labels: V3.3 🍕

#2244 Fix compile error with DEBUG_RCVR_LINKSTATS, move debug code
  src/src/rx_main.cpp
Labels: bug :bug:, V3.3 🍕

#2253 Removing WiFi upload methods from STM targets
  src/hardware/targets.json
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2251 Add BETAFPV Super-P 14Channel PWM Target
  src/hardware/targets.json
Labels: new target :dart:, V3.3 🍕

#2255 Fix no backpack overwriting channels
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2259 Im bringin' gemini back (yeah)... to Airport
  src/lib/LUA/tx_devLUA.cpp
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2257 Increased default UARTrequestedBaud for Airport F1000
  src/lib/CRSF/CRSF.cpp
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2252 ADC attenuation for ESP32 targets
  src/hardware/RX/Frank 2400.json
  src/hardware/RX/Generic 2400 True Diversity PA PWM 14.json
  src/hardware/RX/Generic 2400 True Diversity PWM 16.json
  src/hardware/RX/Generic 900 True Diversity PWM 16.json
  src/hardware/RX/Radiomaster 2400 ER8G.json
  src/hardware/RX/Vario 2400.json
  src/hardware/targets.json
  src/html/hardware.html
  src/include/hardware.h
  src/lib/AnalogVbat/devAnalogVbat.cpp
  src/lib/OPTIONS/hardware.cpp
  src/python/test_tools/power_sweep.py
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2266 Force Telemetry value not displaying in webui due to typo
  src/html/scan.js
Labels: bug :bug:, V3.3 🍕

#2268 ER6-G/GV and ER6/ER8/ER8G/ER8GV VBAT values swapped
  src/hardware/RX/Radiomaster 2400 ER8G.json
  src/hardware/RX/Vario 2400.json
Labels: bug :bug:, V3.3 🍕

#2267 Respect when someone declines to flash the wrong target
  src/python/BFinitPassthrough.py
Labels: bug :bug:, V3.3 🍕

#2265 adds Geprc dual diversity 2.4 g hz rx
  src/hardware/targets.json
Labels: V3.3 🍕

#2258 Change airport packet type to PACKET_TYPE_TLM
  src/lib/OTA/OTA.cpp
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/SX1280Driver/SX1280.cpp
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: V3.3 🍕

#2272 STM32 SX1272 PCB: add to targets.json for configurator
  src/hardware/targets.json
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2271 Fix LBT TLM reception bug
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/SX127xDriver/SX127x.h
  src/lib/SX1280Driver/SX1280.cpp
  src/lib/SX1280Driver/SX1280.h
  src/lib/SX12xxDriverCommon/SX12xxDriverCommon.h
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2273 More fixes for the flasher
  src/python/binary_configurator.py
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2274 Speed bootup of ESP32 RXes without a vario
  src/lib/Baro/baro_spl06.cpp
  src/lib/Baro/baro_spl06.h
Labels: V3.3 🍕

#2281 iFlight 2.4 & 900 V2 TX modules
  src/hardware/TX/iFlight 2400 V2.json
  src/hardware/TX/iFlight 900 V2.json
  src/hardware/targets.json
Labels: new target :dart:, V3.3 🍕
