Repository ExpressLRS/ExpressLRS, pull requests merged in 2023-11, with the labels that each got.

#2425 Configurable I2C pins for PWM capable (ESP32) receivers
  src/html/elrs.css
  src/html/index.html
  src/html/scan.js
  src/include/common.h
  src/lib/Baro/devBaro.cpp
  src/lib/CONFIG/config.cpp
  src/lib/LUA/rx_devLUA.cpp
  src/lib/ServoOutput/devServoOutput.cpp
  src/lib/WIFI/devWIFI.cpp
  src/lua/elrsV3.lua
  src/python/serve_html.py
  src/src/rx_main.cpp
  src/src/rxtx_common.cpp
Labels: enhancement :magic_wand:, V3.4 🍟

#2444 Adds a Joystick that sends data via UDP/WIFI
  src/lib/WIFI/devWIFI.cpp
  src/lib/WIFI/wifiJoystick.cpp
  src/lib/WIFI/wifiJoystick.h
Labels: V3.4 🍟

#2469 fix HARDWARE_led_reg_green spelling
  src/include/hardware.h
  src/include/target/Unified_ESP32_TX.h
  src/include/target/Unified_ESP8285_TX.h
  src/include/target/Unified_ESP_RX.h
  src/lib/OPTIONS/hardware.cpp
Labels: V3.4 🍟, house keeping :broom:

#2478 fix: SUMD not working at packet rates above 100Hz
  src/src/rx-serial/SerialSUMD.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2309 Add US433 regulatory domains
  src/html/index.html
  src/include/targets.h
  src/lib/FHSS/FHSS.cpp
  src/lib/OPTIONS/options.cpp
  src/python/binary_configurator.py
  src/python/build_flags.py
  src/user_defines.txt
Labels: enhancement :magic_wand:, V3.4 🍟

#2472 Fix esp32s3 and backpack passthrough flashing settings
  src/lib/Backpack/devBackpack.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2473 Move unified.ini to top of targets list
  src/platformio.ini
  src/targets/HGLRC_2400.ini
  src/targets/HGLRC_900.ini
  src/targets/Jumper_2400.ini
  src/targets/MATEK_2400.ini
  src/targets/axis_2400.ini
  src/targets/betafpv_2400.ini
  src/targets/betafpv_900.ini
  src/targets/diy_2400.ini
  src/targets/diy_900.ini
  src/targets/diy_ble_joystick.ini
  src/targets/emax_2400.ini
  src/targets/emax_900.ini
  src/targets/foxeer_2400.ini
  src/targets/happymodel_2400.ini
  src/targets/happymodel_900.ini
  src/targets/iFlight_2400.ini
  src/targets/iFlight_900.ini
  src/targets/namimnorc_2400.ini
  src/targets/namimnorc_900.ini
  src/targets/neutronrc_900.ini
  src/targets/quadkopters_2400.ini
  src/targets/radiomaster_2400.ini
  src/targets/vantac_2400.ini
Labels: V3.4 🍟, house keeping :broom:

#2481 Fix github firmware build
  src/python/pyproject.toml
  src/python/setup.py
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2483 stlink flash fix bootloader path
  src/python/binary_flash.py
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2489 Backport "Remove extraneous pyproject.toml file (#2481)"
  src/python/pyproject.toml
  src/python/setup.py
Labels: pick, bugfixes :lady_beetle:, V3.3 🍕

#2486 Fix PWM channel reset on TX/RX serial port config change via LUA
  src/lib/LUA/rx_devLUA.cpp
Labels: bugfixes :lady_beetle:, V3.3 🍕
