Repository ExpressLRS/ExpressLRS, pull requests merged in 2023-02, with the labels that each got.

#2002 Gemini TX/RX antenna alternation
  src/include/common.h
  src/lib/LUA/tx_devLUA.cpp
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: V3.3 🍕

#2074 Fix ER6GV target
  src/hardware/RX/Vario 2400.json
  src/hardware/targets.json
Labels: V3.3 🍕

#2090 Fix logic error introduced in AirPort
  src/src/rx_main.cpp
Labels: bugfixes :lady_beetle:, V3.3 🍕

#1994 Remove InvertIQ for sx127x
  src/lib/SX127xDriver/SX127x.cpp
Labels: V3.3 🍕

#2078 Fix Skystars SS24D target layout
  src/hardware/targets.json
Labels: bugfixes :lady_beetle:, V3.2 :beer:

#2055 Keep system status up to date after EU_LBT channel in use detected
  src/lib/LBT/LBT.cpp
  src/lib/SX127xDriver/SX127x.h
  src/lib/SX1280Driver/SX1280.cpp
  src/lib/SX12xxDriverCommon/SX12xxDriverCommon.h
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V3.2 :beer:
