Repository ExpressLRS/ExpressLRS, pull requests merged in 2023-07, with the labels that each got.

#2283 Increasing the autobaud denominator factor by one (for fixing failed autobaud in some modules)
  src/lib/CRSF/CRSF.cpp
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2282 Wide switch mode + TLM ratio change v.bad interaction
  src/lib/OTA/OTA.cpp
Labels: bug :bug:, V3.3 🍕

#2287 Allow RX to accept telemetry from a TX module
  src/lib/Telemetry/telemetry.cpp
Labels: enhancement :magic_wand:, V3.3 🍕

#2292 Revert "ER6-G/GV and ER6/ER8/ER8G/ER8GV VBAT values swapped"
  src/hardware/RX/Radiomaster 2400 ER8G.json
  src/hardware/RX/Vario 2400.json
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2295 Binary patching of STM based targets broken
  src/lib/OPTIONS/options.cpp
  src/lib/OPTIONS/options.h
  src/python/binary_configurator.py
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2299 Return wifi to R9M upload methods
  src/hardware/targets.json
Labels: V3.3 🍕

#2298 Jumper T-20 2400 and 900 target defines
  src/hardware/TX/Jumper T-20 2400.json
  src/hardware/TX/Jumper T-20 900.json
  src/hardware/targets.json
Labels: new target :dart:, V3.3 🍕

#2303 Further Jumper T-20 power calibration upon CMU200
  src/hardware/TX/Jumper T-20 2400.json
  src/hardware/TX/Jumper T-20 900.json
Labels: V3.3 🍕

#2304 adds HappyModel ES900 Dual RX
  src/hardware/targets.json
Labels: new target :dart:, V3.3 🍕

#2301 add missing isFirstRxIrq to sx127x
  src/lib/SX127xDriver/SX127x.cpp
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2306 Append prior target name to firmware
  src/hardware/targets.json
  src/python/UnifiedConfiguration.py
  src/python/targets_validator.py
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2307 Corrections for BetaFPV Super-P VBAT measurement
  src/hardware/targets.json
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2310 New Sub250 target
  src/hardware/targets.json
Labels: new target :dart:, V3.3 🍕

#2319 Cosmetic tweaks to Target Names
  src/hardware/targets.json
  src/targets/happymodel_2400.ini
Labels: V3.3 🍕

#2327 External module baudrate 400k baud max air-rate is 333Hz
  src/lib/CRSF/CRSF.cpp
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2323 Fix Gemini 900 backpack
  src/hardware/TX/Generic 900 Gemini.json
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2311 Adds a second sx1280 rst pin
  src/hardware/RX/Generic 2400 True Diversity PA and VTx.json
  src/hardware/RX/Generic 2400 True Diversity PA.json
  src/hardware/RX/Generic 2400 True Diversity and VTx.json
  src/hardware/TX/Generic 2400 Gemini.json
  src/html/hardware.html
  src/include/hardware.h
  src/include/target/Unified_ESP32_TX.h
  src/include/target/Unified_ESP8285_TX.h
  src/include/target/Unified_ESP_RX.h
  src/include/targets.h
  src/lib/OPTIONS/hardware.cpp
  src/lib/SX1280Driver/SX1280_hal.cpp
Labels: V3.4 🍟
