Repository ExpressLRS/ExpressLRS, pull requests merged in 2023-10, with the labels that each got.

#2427 Typo fix in PWM.h
  src/lib/PWM/PWM.h
Labels: V3.4 🍟, house keeping :broom:

#2436 fix RSNR after #2399
  src/lib/SX12xxDriverCommon/SX12xxDriverCommon.h
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2430 Fix LBT fall back mode
  src/lib/SX1280Driver/SX1280.cpp
  src/lib/SX1280Driver/SX1280.h
Labels: V3.3 🍕

#2413 Optimize and fix broken FM30 target
  src/include/target/FM30_TX.h
  src/lib/BUTTON/button.h
  src/lib/LUA/lua.h
  src/lib/LUA/tx_devLUA.cpp
  src/lib/OTA/OTA.h
  src/lib/SCREEN/fsm.h
  src/src/tx_main.cpp
  src/targets/siyi.ini
Labels: bug :bug:, V3.3 🍕

#2433 Allow separate firmware dir to targets dir
  src/python/binary_configurator.py
Labels: V3.3 🍕

#2431 SPIEx on ESP32 was using the wrong underlying bus!
  src/lib/SPIEx/SPIEx.cpp
  src/lib/VTXSPI/devVTXSPI.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2432 OLED/TFT menu updates
  src/lib/SCREEN/OLED/XBMStrings.h
  src/lib/SCREEN/OLED/oleddisplay.cpp
  src/lib/SCREEN/TFT/logos.h
  src/lib/SCREEN/TFT/tftdisplay.cpp
  src/lib/SCREEN/display.cpp
  src/lib/SCREEN/menu.cpp
  src/lib/SCREEN/menu.h
  src/targets/unified.ini
Labels: enhancement :magic_wand:, V3.4 🍟

#2422 Various web UI fixes and improvements
  src/html/elrs.css
  src/html/hardware.html
  src/html/hardware.js
  src/html/index.html
  src/html/scan.js
  src/lib/OPTIONS/options.cpp
  src/python/serve_html.py
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2438 puts the fix for #2028 back into business - 3.x.x-maintenance
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2429 Hide lua backpack items if the backpack is disabled
  src/lib/LUA/lua.h
  src/lib/LUA/tx_devLUA.cpp
  src/lua/elrsV3.lua
Labels: V3.4 🍟

#2423 Fixes for LEDC driven PWM channels on ESP32
  src/lib/PWM/PWM_ESP32.cpp
  src/lib/ServoOutput/devServoOutput.cpp
  src/lib/ServoOutput/devServoOutput.h
  src/lib/logging/logging.h
  src/src/rx_main.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2442 fifo: avoid overflowing size argument
  src/lib/FIFO/FIFO.h
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2445 Oops, undo setting the out directory
  src/python/binary_configurator.py
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2455 Add channels 15 and 16 to mavlink output
  src/src/rx-serial/SerialMavlink.cpp
Labels: MAVLink

#2454 Add SS for the uplink mav data
  src/lib/MSP/msptypes.h
  src/lib/OTA/OTA.h
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: MAVLink

#2424 Automatically save the RX initial rate on disconnect
  src/lib/LUA/rx_devLUA.cpp
  src/src/rx_main.cpp
Labels: enhancement :magic_wand:, V3.4 🍟

#2451 3.x.x merge to master
  src/include/target/FM30_TX.h
  src/lib/BUTTON/button.h
  src/lib/CRSF/CRSF.cpp
  src/lib/LUA/lua.h
  src/lib/LUA/tx_devLUA.cpp
  src/lib/OTA/OTA.h
  src/lib/POWERMGNT/POWERMGNT.h
  src/lib/SCREEN/fsm.h
  src/lib/SCREEN/menu.cpp
  src/lib/SX1280Driver/SX1280.cpp
  src/lib/SX1280Driver/SX1280.h
  src/lib/SX12xxDriverCommon/SX12xxDriverCommon.h
  src/python/binary_configurator.py
  src/python/binary_flash.py
  src/src/rx_main.cpp
  src/src/tx_main.cpp
  src/targets/happymodel_2400.ini
  src/targets/siyi.ini
Labels: DO NOT SQUASH MERGE, V3.4 🍟

#2459 chore: adapt serial protocol labels in WebUI and LUA script
  src/html/index.html
Labels: V3.4 🍟, house keeping :broom:

#2458 Set defaults for testers - DELETE ME LATER
  src/src/rx_main.cpp
  src/src/tx_main.cpp
  src/user_defines.txt
Labels: MAVLink
