Repository ExpressLRS/ExpressLRS, pull requests merged in 2023-04, with the labels that each got.

#2154 Merge 3.x.x into master
  src/hardware/TX/EMAX 900 Nano.json
  src/hardware/TX/EMAX 900 OLED.json
  src/hardware/targets.json
  src/html/index.html
  src/html/scan.js
  src/lib/LBT/LBT.cpp
  src/lib/LUA/tx_devLUA.cpp
  src/lib/OPTIONS/options.cpp
  src/lib/POWERMGNT/POWERMGNT.cpp
  src/lib/POWERMGNT/POWERMGNT.h
  src/lib/POWER_DETECT/devPDET.cpp
  src/lib/SCREEN/menu.cpp
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/SX1280Driver/SX1280.cpp
  src/lib/SX12xxDriverCommon/SX12xxDriverCommon.h
  src/lib/Telemetry/telemetry.cpp
  src/lib/WIFI/devWIFI.cpp
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: DO NOT SQUASH MERGE, V3.3 🍕

#2137 Additional serial protocol: Graupner HoTT SUMD
  src/html/index.html
  src/html/scan.js
  src/include/common.h
  src/lib/CONFIG/config.h
  src/lib/LUA/rx_devLUA.cpp
  src/lib/OPTIONS/options.cpp
  src/src/rx-serial/SerialSUMD.cpp
  src/src/rx-serial/SerialSUMD.h
  src/src/rx_main.cpp
Labels: V3.3 🍕

#2144 Fix attenuation for some ESP32 pins
  src/lib/AnalogVbat/devAnalogVbat.cpp
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2151 Update tag for "closing" stale issues.
  .github/workflows/stale.yml
Labels: V3.3 🍕

#2155 Remove redundant code post maint merge
  src/lib/SX127xDriver/SX127x.cpp
Labels: V3.3 🍕

#2147 900M True Diversity PWM16
  src/hardware/RX/Generic 900 True Diversity PWM 16.json
  src/hardware/targets.json
Labels: V3.3 🍕

#2060 Wireless Head Tracker
  src/lib/Backpack/devBackpack.cpp
  src/lib/Backpack/devBackpack.h
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/LUA/tx_devLUA.cpp
  src/lib/MSP/msptypes.h
  src/src/tx_main.cpp
Labels: V3.3 🍕

#2161 tempFC was wrongly set unsigned
  src/src/common.cpp
  src/src/rx_main.cpp
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2167 Fix RF power-creep on TTGOv2 TX
  src/hardware/TX/DIY 900 TTGO V2.json
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2143 True diversity rssi update on both radio
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/SX127xDriver/SX127x.h
  src/lib/SX1280Driver/SX1280.cpp
  src/lib/SX1280Driver/SX1280.h
  src/lib/SX12xxDriverCommon/SX12xxDriverCommon.h
  src/src/rx_main.cpp
  src/src/tx_main.cpp
  src/targets/siyi.ini
  src/user_defines.txt
Labels: For Discussion :mega:, V3.3 🍕

#2174 Fix error reporting wifi case
  src/lib/WIFI/devWIFI.cpp
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2170 Max rate of external module on 115k baud is 150Hz
  src/include/common.h
  src/lib/CRSF/CRSF.cpp
  src/lib/CRSF/CRSF.h
  src/src/tx_main.cpp
Labels: V3.3 🍕

#2179 Adds newbeedrone 2400 rx
  src/hardware/targets.json
Labels: new target :dart:, V3.3 🍕

#2007 MSP VTX device
  src/.DS_Store
  src/hardware/RX/Generic 2400 True Diversity PA and VTx.json
  src/hardware/RX/Generic 2400 True Diversity and VTx.json
  src/hardware/RX/Generic 2400 Whoop Rx and VTx.json
  src/include/target/Unified_ESP_RX.h
  src/include/targets.h
  src/lib/CRSF/CRSF.cpp
  src/lib/CRSF/CRSF.h
  src/lib/CrsfProtocol/crsf_protocol.h
  src/lib/MSP/msptypes.h
  src/lib/MSPVTX/devMSPVTX.cpp
  src/lib/MSPVTX/devMSPVTX.h
  src/lib/MSPVTX/freqTable.cpp
  src/lib/MSPVTX/freqTable.h
  src/lib/SerialUpdate/devSerialUpdate.cpp
  src/lib/Telemetry/telemetry.cpp
  src/lib/VTXSPI/devVTXSPI.cpp
  src/lib/VTXSPI/devVTXSPI.h
  src/lib/WIFI/devWIFI.cpp
  src/python/BFinitPassthrough.py
  src/src/rx_main.cpp
  src/test/test_msp_vtx/msp_vtx_tests.cpp
Labels: V3.3 🍕

#2180 Adds Happymodel EPW5 and EPW6 targets
  src/hardware/targets.json
Labels: new target :dart:, V3.3 🍕

#2177 fix rx lua luaTlmPower
  src/lib/LUA/rx_devLUA.cpp
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2149 Always use flashed options after a new flash
  src/html/elrs.css
  src/html/index.html
  src/html/scan.js
  src/lib/OPTIONS/options.cpp
  src/lib/OPTIONS/options.h
  src/lib/WIFI/devWIFI.cpp
  src/python/binary_configurator.py
  src/python/build_flags.py
  src/python/serve_html.py
  src/targets/common.ini
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2178 esp32 rx - allow non uart0 pins for serial setup
  src/src/rx_main.cpp
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2145 Package the python directory into a flasher package with shiv
  .github/workflows/artifacts.yml
  .github/workflows/build.yml
  src/python/MANIFEST.in
  src/python/__init__.py
  src/python/__main__.py
  src/python/binary_configurator.py
  src/python/binary_flash.py
  src/python/build_env_setup.py
  src/python/external/__init__.py
  src/python/external/esptool/__init__.py
  src/python/firmware.py
  src/python/pyproject.toml
  src/python/setup.py
Labels: V3.3 🍕
