Repository ExpressLRS/ExpressLRS, pull requests merged in 2023-12, with the labels that each got.

#2491 Revert LinkStatistics changes
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2499 Retain PWM channel setting when switching a serial pin function
  src/lib/LUA/rx_devLUA.cpp
Labels: bugfixes :lady_beetle:, V3.4 :chocolate_bar:

#2496 Fix for 10KHz 0% and 100% on 8285 receivers
  src/lib/ServoOutput/waveform_8266.cpp
Labels: bugfixes :lady_beetle:, V3.4 :chocolate_bar:

#2506 Cherry pick pull request #2444 to 3.x.x
  src/lib/WIFI/devWIFI.cpp
  src/lib/WIFI/wifiJoystick.cpp
  src/lib/WIFI/wifiJoystick.h
Labels: enhancement :magic_wand:, V3.4 :chocolate_bar:

#2498 Ability to set Semtech output power when using DAC for PA power control
  src/html/hardware.html
  src/include/hardware.h
  src/include/target/DIY_900_RX_STM32.h
  src/include/target/DIY_900_RX_STM32_SX1272.h
  src/include/target/DIY_900_TX_STM32_SX1272.h
  src/include/target/Frsky_RX_R9M.h
  src/include/target/Frsky_TX_R9M_LITE.h
  src/include/target/NamimnoRC_VOYAGER_900_RX.h
  src/include/target/Unified_ESP32_TX.h
  src/include/target/Unified_ESP_RX.h
  src/lib/OPTIONS/hardware.cpp
  src/lib/POWERMGNT/POWERMGNT.cpp
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/SX127xDriver/SX127x.h
  src/lib/SX127xDriver/SX127xRegs.h
Labels: enhancement :magic_wand:, V3.4 :chocolate_bar:

#2511 Pin AsyncTCP to specific version
  src/targets/common.ini
Labels: bugfixes :lady_beetle:, V3.4 🍟
