Repository ExpressLRS/ExpressLRS, pull requests merged in 2023-09, with the labels that each got.

#2387 Fix ESP8285 RX as TX
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2385 Fix missing FIFO debug method
  src/lib/FIFO/FIFO.h
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2393 Allow binary flash of DUPLETX_ESP
  src/python/binary_flash.py
Labels: bug :bug:, V3.3 🍕

#2322 Configurable OLED/TFT startup splash screen
  src/hardware/logo/README.md
  src/hardware/logo/axis_tft.bin
  src/hardware/logo/betafpv.bin
  src/hardware/logo/elrs32.bin
  src/hardware/logo/elrs64.bin
  src/hardware/logo/emax.bin
  src/hardware/logo/geprc_tft.bin
  src/hardware/logo/jumper.bin
  src/hardware/logo/namimno.bin
  src/hardware/logo/radiomaster.bin
  src/hardware/targets.json
  src/lib/DEVICE/device.cpp
  src/lib/OPTIONS/options.cpp
  src/lib/OPTIONS/options.h
  src/lib/SCREEN/OLED/oleddisplay.cpp
  src/lib/SCREEN/TFT/logos.h
  src/lib/SCREEN/TFT/tftdisplay.cpp
  src/python/UnifiedConfiguration.py
Labels: enhancement :magic_wand:, V3.4 🍟

#2370 Sentinel tracker integration
  src/lib/Backpack/devBackpack.cpp
  src/lib/Backpack/devBackpack.h
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/LUA/tx_devLUA.cpp
  src/lib/MSP/msp.h
  src/lib/MSP/msptypes.h
  src/src/tx_main.cpp
Labels: enhancement :magic_wand:, V3.4 🍟

#2242 Add "MatchTX" RX dynamic output power
  src/include/dynpower.h
  src/lib/CRSF/CRSF.cpp
  src/lib/CRSF/CRSF.h
  src/lib/LUA/rx_devLUA.cpp
  src/lib/LUA/rxtx_devLua.cpp
  src/lib/OTA/OTA.cpp
  src/lib/POWERMGNT/POWERMGNT.cpp
  src/lib/POWERMGNT/POWERMGNT.h
  src/src/dynpower.cpp
  src/src/rx_main.cpp
Labels: enhancement :magic_wand:, V3.4 🍟

#2396 Add LinkStats to ESPNOW MSP Backpack Telemetry
  src/lib/CRSF/CRSF.cpp
  src/lib/CRSF/CRSF.h
  src/src/tx_main.cpp
Labels: enhancement :magic_wand:, V3.4 🍟

#2384 ESP32(S2/3) specific RGB driver
  src/lib/LED/devRGB.cpp
  src/lib/LED/esp32rgb.cpp
  src/lib/LED/esp32rgb.h
  src/targets/common.ini
Labels: enhancement :magic_wand:, V3.4 🍟

#2399 hadling div/0 condition in `fuzzy_snr()`
  src/lib/SX12xxDriverCommon/SX12xxDriverCommon.h
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2339 SPI Optimisations
  src/include/targets.h
  src/lib/SPIEx/SPIEx.cpp
  src/lib/SPIEx/SPIEx.h
  src/lib/SX127xDriver/SX127xHal.cpp
  src/lib/SX127xDriver/SX127xHal.h
  src/lib/SX1280Driver/SX1280_hal.cpp
  src/lib/SX1280Driver/SX1280_hal.h
  src/platformio.ini
Labels: enhancement :magic_wand:, V3.4 🍟

#2391 Hardware timer cleanup and API documentation
  src/lib/HWTIMER/ESP32_hwTimer.cpp
  src/lib/HWTIMER/ESP32_hwTimer.h
  src/lib/HWTIMER/ESP8266_hwTimer.cpp
  src/lib/HWTIMER/ESP8266_hwTimer.h
  src/lib/HWTIMER/STM32_hwTimer.cpp
  src/lib/HWTIMER/STM32_hwTimer.h
  src/lib/HWTIMER/hwTimer.h
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: V3.4 🍟, house keeping :broom:

#2388 Ability to set Semtech output power when using DAC for PA power control
  src/hardware/RX/DIY 900 TTGO V1.json
  src/hardware/RX/DIY 900 TTGO V2.json
  src/hardware/RX/DIY Huzzah RFM95.json
  src/hardware/RX/Generic 900 PWMP.json
  src/hardware/RX/Generic 900 True Diversity PA.json
  src/hardware/RX/Generic 900 True Diversity PWM 16.json
  src/hardware/RX/Generic 900.json
  src/hardware/RX/Namimno VOYAGER 900.json
  src/hardware/TX/DIY 900 E19.json
  src/hardware/TX/DIY 900 RFM95.json
  src/hardware/TX/DIY 900 TTGO V1.json
  src/hardware/TX/DIY 900 TTGO V2.json
  src/hardware/TX/Generic 900 Gemini.json
  src/hardware/TX/Jumper T-20 900.json
  src/html/hardware.html
  src/include/hardware.h
  src/include/target/DIY_900_RX_STM32.h
  src/include/target/DIY_900_RX_STM32_SX1272.h
  src/include/target/DIY_900_TX_STM32_SX1272.h
  src/include/target/Frsky_RX_R9M.h
  src/include/target/Frsky_TX_R9M_LITE.h
  src/include/target/NamimnoRC_VOYAGER_900_RX.h
  src/include/target/Unified_ESP32_TX.h
  src/include/target/Unified_ESP_RX.h
  src/lib/OPTIONS/hardware.cpp
  src/lib/POWERMGNT/POWERMGNT.cpp
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/SX127xDriver/SX127x.h
  src/lib/SX127xDriver/SX127xRegs.h
Labels: enhancement :magic_wand:, V3.4 🍟

#2383 RX Serial cleanup and documentation
  src/src/rx-serial/SerialAirPort.cpp
  src/src/rx-serial/SerialAirPort.h
  src/src/rx-serial/SerialCRSF.cpp
  src/src/rx-serial/SerialCRSF.h
  src/src/rx-serial/SerialIO.cpp
  src/src/rx-serial/SerialIO.h
  src/src/rx-serial/SerialNOOP.h
  src/src/rx-serial/SerialSBUS.cpp
  src/src/rx-serial/SerialSBUS.h
  src/src/rx-serial/SerialSUMD.cpp
  src/src/rx-serial/SerialSUMD.h
  src/src/rx-serial/devSerialIO.cpp
  src/src/rx_main.cpp
Labels: V3.4 🍟, house keeping :broom:

#2386 Extract and create new PWM library
  src/lib/PWM/PWM.cpp
  src/lib/PWM/PWM.h
  src/lib/PWM/PWM_ESP32.cpp
  src/lib/PWM/PWM_ESP8266.cpp
  src/lib/PWM/waveform_8266.cpp
  src/lib/PWM/waveform_8266.h
  src/lib/ServoOutput/ServoMgr.cpp
  src/lib/ServoOutput/ServoMgr.h
  src/lib/ServoOutput/devServoOutput.cpp
  src/lib/ServoOutput/devServoOutput.h
  src/lib/ServoOutput/waveform_8266.h
  src/platformio.ini
  src/targets/common.ini
Labels: enhancement :magic_wand:, V3.4 🍟

#2410 Add ESP32-S3 support
  src/include/target/Unified_ESP_RX.h
  src/lib/AnalogVbat/devAnalogVbat.cpp
  src/lib/CRSF/CRSF.cpp
  src/lib/POWERMGNT/POWERMGNT.cpp
  src/lib/SPIEx/SPIEx.cpp
  src/lib/VTXSPI/devVTXSPI.cpp
  src/lib/logging/logging.h
  src/python/UnifiedConfiguration.py
  src/python/binary_configurator.py
  src/src/rx_main.cpp
  src/src/tx_main.cpp
  src/targets/common.ini
  src/targets/unified.ini
  src/user_defines.txt
Labels: enhancement :magic_wand:, V3.4 🍟

#2415 Add float support to Lua
  src/lib/LUA/lua.h
  src/lib/LUA/tx_devLUA.cpp
  src/lua/elrsV3.lua
  src/lua/mockup/elrsmock.lua
Labels: enhancement :magic_wand:, V3.4 🍟

#2409 Remove the UART_INVERTED option
  src/html/index.html
  src/lib/CRSF/CRSF.cpp
  src/lib/OPTIONS/options.cpp
  src/lib/OPTIONS/options.h
  src/lib/WIFI/devWIFI.cpp
  src/python/binary_configurator.py
  src/python/build_flags.py
  src/user_defines.txt
Labels: V3.4 🍟, house keeping :broom:

#2408 Support Graupner HoTT telemetry sensors
  src/html/index.html
  src/include/common.h
  src/lib/Baro/devBaro.cpp
  src/lib/LUA/rx_devLUA.cpp
  src/lib/OPTIONS/options.cpp
  src/lib/Telemetry/telemetry.cpp
  src/lib/Telemetry/telemetry.h
  src/src/rx-serial/SerialHoTT_TLM.cpp
  src/src/rx-serial/SerialHoTT_TLM.h
  src/src/rx_main.cpp
Labels: enhancement :magic_wand:, V3.4 🍟

#2417 Fix ESP32 timer after cleanup PR
  src/lib/HWTIMER/ESP32_hwTimer.cpp
  src/lib/HWTIMER/ESP8266_hwTimer.cpp
  src/lib/HWTIMER/STM32_hwTimer.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2407 Fix debugging the timer offsets
  src/lib/HWTIMER/hwTimer.h
  src/src/rx_main.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2416 Fix Lua for SELECT types with only one value
  src/lua/elrsV3.lua
Labels: bug :bug:, V3.4 🍟

#2346 Adding DShot Output to ESP32-based ELRS PWM Receivers
  src/html/scan.js
  src/include/common.h
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/CONFIG/config_legacy.h
  src/lib/LUA/rx_devLUA.cpp
  src/lib/ServoOutput/DShotRMT.cpp
  src/lib/ServoOutput/DShotRMT.h
  src/lib/ServoOutput/devServoOutput.cpp
  src/lib/ServoOutput/devServoOutput.h
  src/lib/WIFI/devWIFI.cpp
Labels: enhancement :magic_wand:, V3.4 🍟
