Repository ExpressLRS/ExpressLRS, pull requests merged in 2023-05, with the labels that each got.

#2187 Disable MSPVTX if theres to SPI VTX
  src/lib/MSPVTX/devMSPVTX.cpp
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2184 Fix airport baud-rate not editable
  src/html/scan.js
  src/python/serve_html.py
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2166 Web UI button fix
  src/html/scan.js
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2183 Reduce screen update frequency when running Lua
  src/lua/elrsV3.lua
Labels: V3.3 🍕

#2186 Implement failsafe modes for SBUS
  src/html/index.html
  src/html/scan.js
  src/include/common.h
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/LUA/rx_devLUA.cpp
  src/lib/WIFI/devWIFI.cpp
  src/python/serve_html.py
  src/src/rx-serial/SerialIO.cpp
  src/src/rx-serial/SerialIO.h
  src/src/rx-serial/SerialSBUS.cpp
  src/src/rx-serial/devSerialIO.cpp
Labels: V3.3 🍕

#2140 DJI RS 2 Sbus Support
  src/html/index.html
  src/include/common.h
  src/lib/LUA/rx_devLUA.cpp
  src/lib/OPTIONS/options.cpp
  src/src/rx-serial/SerialSBUS.cpp
  src/src/rx_main.cpp
Labels: V3.3 🍕

#2196 Binary flashing fixes
  src/hardware/targets.json
  src/python/binary_configurator.py
  src/python/binary_flash.py
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2203 Remove INFOLN
  src/lib/FHSS/FHSS.cpp
  src/lib/logging/logging.h
  src/src/rx_main.cpp
Labels: V3.3 🍕

#2205 Fix displayed UART baud in airport & CRSF mode
  src/html/scan.js
  src/lib/CRSF/devCRSF_tx.cpp
  src/lib/OPTIONS/options.h
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2197 Add pystlink/pyusb to binary flasher
  src/python/binary_flash.py
  src/python/external/pystlink/__init__.py
  src/python/external/pystlink/bin/install.bat
  src/python/external/pystlink/bin/libusb-1.0.dll
  src/python/external/pystlink/lib/__init__.py
  src/python/external/pystlink/lib/dbg.py
  src/python/external/pystlink/lib/srec.py
  src/python/external/pystlink/lib/stlinkex.py
  src/python/external/pystlink/lib/stlinkusb.py
  src/python/external/pystlink/lib/stlinkv2.py
  src/python/external/pystlink/lib/stm32.py
  src/python/external/pystlink/lib/stm32devices.py
  src/python/external/pystlink/lib/stm32fp.py
  src/python/external/pystlink/lib/stm32fs.py
  src/python/external/pystlink/lib/stm32h7.py
  src/python/external/pystlink/lib/stm32l0.py
  src/python/external/pystlink/lib/stm32l4.py
  src/python/external/pystlink/list_new_stm32.py
  src/python/external/pystlink/pystlink
  src/python/external/pystlink/pystlink_api.py
  src/python/external/pystlink/stlinkv2.rules
  src/python/external/usb/__init__.py
  src/python/external/usb/_debug.py
  src/python/external/usb/_interop.py
  src/python/external/usb/_lookup.py
  src/python/external/usb/_objfinalizer.py
  src/python/external/usb/_version.py
  src/python/external/usb/backend/__init__.py
  src/python/external/usb/backend/libusb0.py
  src/python/external/usb/backend/libusb1.py
  src/python/external/usb/backend/openusb.py
  src/python/external/usb/control.py
  src/python/external/usb/core.py
  src/python/external/usb/legacy.py
  src/python/external/usb/libloader.py
  src/python/external/usb/util.py
Labels: V3.3 🍕

#2209 add power_apc pins to web UI
  src/html/hardware.html
  src/include/hardware.h
  src/include/target/Unified_ESP32_TX.h
  src/include/target/Unified_ESP8285_TX.h
  src/include/target/Unified_ESP_RX.h
Labels: bugfixes :lady_beetle:

#2207 Increase maximum number of Lua params
  src/lib/LUA/lua.cpp
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2211 Respect model match on all protocols
  src/src/rx-serial/devSerialIO.cpp
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2215 Fix for airport to enable CRSF communication
  src/lib/CRSF/devCRSF_tx.cpp
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2216 Optimise airport serial communications
  src/src/rx-serial/SerialAirPort.cpp
  src/src/rx-serial/SerialAirPort.h
  src/src/rx-serial/SerialIO.cpp
  src/src/rx-serial/SerialIO.h
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2218 More complete fail_count calculation
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/SX1280Driver/SX1280.cpp
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2222 Proper fix for OLED rate change
  src/lib/SCREEN/menu.cpp
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2220 Fix head tracking `ON` selection
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2219 Add SX1272 TX/RX PCB and fix SX1272 build issue
  src/bootloader/src/platformio.ini
  src/bootloader/sx1272_pcb_bootloader.bin
  src/include/target/DIY_900_RX_STM32_SX1272.h
  src/include/target/DIY_900_TX_STM32_SX1272.h
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/SX127xDriver/SX127xRegs.h
  src/targets/diy_900.ini
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2224 Binary flasher fixes
  src/hardware/targets.json
  src/python/UnifiedConfiguration.py
  src/python/binary_configurator.py
  src/python/binary_flash.py
  src/python/targets_validator.py
Labels: V3.3 🍕

#2229 discriminator was small due to bug!
  src/python/binary_configurator.py
  src/python/build_flags.py
Labels: bugfixes :lady_beetle:, V3.3 🍕

#2227 Fix BF passthrough STM binary flashing
  src/python/BFinitPassthrough.py
  src/python/binary_flash.py
Labels: bugfixes :lady_beetle:, V3.3 🍕
