Repository ExpressLRS/ExpressLRS, pull requests merged in 2024-07, with the labels that each got.

#2821 Fixes Arduino core Serial0 being stuck on inverted signal polarity after previous inversion
  src/src/rx_main.cpp
Labels: bugfixes :lady_beetle:, V3.5 🍩

#2789 LR1121 FSK
  src/include/common.h
  src/lib/LR1121Driver/LR1121.cpp
  src/lib/LR1121Driver/LR1121.h
  src/lib/LR1121Driver/LR1121_Regs.h
  src/lib/LUA/tx_devLUA.cpp
  src/lib/SX12xxDriverCommon/SX12xxDriverCommon.h
  src/platformio.ini
  src/src/common.cpp
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: enhancement :magic_wand:, V3.5 🍩

#2823 fix DEBUG_TX_FREERUN
  src/lib/Handset/devHandset.cpp
  src/lib/Handset/handset.h
Labels: bugfixes :lady_beetle:, V3.5 🍩

#2744 Binding Storage Returnable
  src/html/index.html
  src/html/scan.js
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/LED/devLED.cpp
  src/lib/LUA/lua.h
  src/lib/LUA/rx_devLUA.cpp
  src/lib/WIFI/devWIFI.cpp
  src/src/rx_main.cpp
Labels: enhancement :magic_wand:, V3.5 🍩

#2816 devSerialIO refactor
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/src/rx-serial/devSerial1IO.cpp
  src/src/rx-serial/devSerial1IO.h
  src/src/rx-serial/devSerialIO.cpp
  src/src/rx-serial/devSerialIO.h
  src/src/rx_main.cpp
Labels: house keeping :broom:, V3.5 🍩

#2813 luaLinkMode - protect from change while connected
  src/lib/LUA/tx_devLUA.cpp
Labels: MAVLink

#2818 Fix mavlink for internal modules
  src/src/tx_main.cpp
Labels: MAVLink

#2787 RX LUA: make (SBUS) Failsafe Mode line visible
  src/html/index.html
  src/include/common.h
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/LUA/rx_devLUA.cpp
  src/lib/WIFI/devWIFI.cpp
  src/src/rx_main.cpp
Labels: enhancement :magic_wand:, V3.5 🍩

#2842 add bleJoystick as a button event
  src/html/scan.js
  src/include/common.h
  src/lib/BLE/devBLE.cpp
  src/lib/SCREEN/devScreen.cpp
  src/lib/SCREEN/menu.cpp
  src/lib/WIFI/devWIFI.cpp
Labels: enhancement :magic_wand:, V3.5 🍩

#2845 Refactor to resolve web flashing failure after optimization
  src/lib/Handset/CRSFHandset.cpp
  src/lib/Handset/CRSFHandset.h
Labels: bugfixes :lady_beetle:, V3.5 🍩

#2839 Remove two sources of telemetry startup hangs
  src/lib/StubbornReceiver/stubborn_receiver.cpp
  src/lib/StubbornSender/stubborn_sender.cpp
  src/lib/StubbornSender/stubborn_sender.h
  src/test/test_stubborn/test_stubborn.cpp
Labels: enhancement :magic_wand:, bugfixes :lady_beetle:, V3.5 🍩

#2835 Add native Tramp VTX support
  src/html/index.html
  src/include/common.h
  src/lib/LUA/rx_devLUA.cpp
  src/src/rx-serial/SerialTramp.cpp
  src/src/rx-serial/SerialTramp.h
  src/src/rx_main.cpp
Labels: enhancement :magic_wand:, V3.5 🍩

#2848 Downgrade wifi power for 8285 based devices
  src/lib/WIFI/devWIFI.cpp
Labels: V3.5 🍩

#2846 MAVLink: only use a single com buffer from MAVLink include
  src/lib/MAVLink/MAVLink.h
  src/src/rx-serial/SerialMavlink.cpp
Labels: MAVLink, V3.5 🍩

#2850 Fix lua lockup on launch due to previously-used function name
  src/lua/elrsV3.lua
Labels: bugfixes :lady_beetle:, V3.5 🍩

#2824 LR1121 RF Switch Configuration
  src/html/hardware.html
  src/include/hardware.h
  src/include/target/Unified_ESP32_TX.h
  src/include/target/Unified_ESP_RX.h
  src/lib/LR1121Driver/LR1121.cpp
  src/lib/OPTIONS/hardware.cpp
  src/platformio.ini
  src/targets/common.ini
  src/targets/imrc.ini
Labels: enhancement :magic_wand:, V3.5 🍩

#2832 LR1121 - Adds FEC to 2.4GHz FSK
  src/lib/FEC/COPYING
  src/lib/FEC/COPYING.LESSER
  src/lib/FEC/FEC.cpp
  src/lib/FEC/FEC.h
  src/lib/FEC/hamming.cpp
  src/lib/FEC/hamming.h
  src/lib/LR1121Driver/LR1121.cpp
  src/lib/LR1121Driver/LR1121.h
  src/lib/LUA/tx_devLUA.cpp
  src/lib/SX12xxDriverCommon/SX12xxDriverCommon.h
  src/src/common.cpp
Labels: enhancement :magic_wand:, V3.5 🍩

#2826 Allow flashing an RX as a TX
  src/python/UnifiedConfiguration.py
  src/python/binary_configurator.py
  src/python/firmware.py
Labels: enhancement :magic_wand:, V3.5 🍩

#2825 LR1121 firmware upload
  src/html/lr1121.html
  src/html/lr1121.js
  src/lib/LR1121Driver/LR1121_Regs.h
  src/lib/LR1121Driver/LR1121_hal.cpp
  src/lib/LR1121Driver/LR1121_hal.h
  src/lib/WIFI/devWIFI.cpp
  src/lib/WIFI/lr1121.cpp
  src/lib/WIFI/lr1121.h
  src/python/build_html.py
  src/python/serve_html.py
Labels: enhancement :magic_wand:, V3.5 🍩

#2851 Optimise SPI VTX startup (no delay)
  src/lib/VTXSPI/devVTXSPI.cpp
Labels: house keeping :broom:, V3.5 🍩

#2843 Add linkstats to module display
  src/lib/CrsfProtocol/crsf_protocol.h
  src/lib/Handset/CRSF.cpp
  src/lib/Handset/CRSF.h
  src/lib/Handset/CRSFHandset.cpp
  src/lib/Handset/CRSFHandset.h
  src/lib/SCREEN/OLED/oleddisplay.cpp
  src/lib/SCREEN/OLED/oleddisplay.h
  src/lib/SCREEN/TFT/tftdisplay.cpp
  src/lib/SCREEN/TFT/tftdisplay.h
  src/lib/SCREEN/devScreen.cpp
  src/lib/SCREEN/display.h
  src/lib/SCREEN/menu.cpp
  src/lib/SCREEN/menu.h
  src/lib/WIFI/devWIFI.cpp
  src/src/rx-serial/SerialCRSF.cpp
  src/src/rx-serial/SerialSBUS.cpp
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: enhancement :magic_wand:, V3.5 🍩

#2858 Use mavlink_frame_char on RX MAVLink, which seems to be better in testing from Backpack
  src/lib/MAVLink/MAVLink.cpp
  src/src/rx-serial/SerialMavlink.cpp
Labels: MAVLink, V3.5 🍩

#2822 Mavlink - Configure Tx modules to work as standalone transmitters without a handset
  src/lib/MAVLink/MAVLink.cpp
  src/lib/MAVLink/MAVLink.h
  src/src/tx_main.cpp
Labels: MAVLink, V3.5 🍩

#2814 Mavlink - disable tlm and switch options in Lua
  src/lib/LUA/tx_devLUA.cpp
  src/lua/elrsV3.lua
  src/lua/mockup/elrsmock.lua
Labels: MAVLink, V3.5 🍩

#2865 Fix failsafe never getting set
  src/src/rx-serial/devSerialIO.cpp
Labels: bugfixes :lady_beetle:, V3.5 🍩

#2870 Unremove firmwareOptions uid when customizing
  src/lib/OPTIONS/options.cpp
Labels: bugfixes :lady_beetle:, V3.5 🍩
