Repository ExpressLRS/ExpressLRS, pull requests merged in 2024-08, with the labels that each got.

#2868 Update MAVLink to CRSF
  src/lib/MAVLink/MAVLink.cpp
Labels: bugfixes :lady_beetle:, V3.5 🍩

#2867 Allow Backpack in MAVLink mode to come back to Normal mode automatically
  src/lib/Backpack/devBackpack.cpp
  src/lib/MAVLink/MAVLink.cpp
  src/lib/MAVLink/MAVLink.h
Labels: V3.5 🍩

#2884 Fix LR1121 binding compatibility
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V3.5 🍩

#2883 Parse MSP messages from the backpack while TX is in mavlink mode
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, MAVLink, V3.5 🍩

#2885 Extend Backpack telemetry forwarding options
  src/lib/Backpack/devBackpack.cpp
  src/lib/Backpack/devBackpack.h
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/LUA/tx_devLUA.cpp
  src/lib/MSP/msptypes.h
  src/src/tx_main.cpp
Labels: MAVLink, V3.5 🍩

#2894 Fix betaflight passthrough erase flash
  src/python/binary_flash.py
Labels: bugfixes :lady_beetle:, V3.5 🍩

#2893 Reduces RMT clock for PPM input so it works on S3 devices as well
  src/lib/Handset/AutoDetect.cpp
  src/lib/Handset/PPMHandset.cpp
Labels: bugfixes :lady_beetle:, V3.5 🍩

#2897 Fix disabling of wifi-auto-on-internal
  src/lib/OPTIONS/options.cpp
  src/lib/WIFI/devWIFI.cpp
Labels: bugfixes :lady_beetle:, V3.5 🍩
