Repository ExpressLRS/ExpressLRS, pull requests merged in 2024-12, with the labels that each got.

#3049 Device/event framework optimisation
  src/include/common.h
  src/lib/AnalogVbat/devAnalogVbat.cpp
  src/lib/BLE/devBLE.cpp
  src/lib/BUTTON/devButton.cpp
  src/lib/Backpack/devBackpack.cpp
  src/lib/Baro/devBaro.cpp
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/DEVICE/device.cpp
  src/lib/DEVICE/device.h
  src/lib/GSENSOR/devGsensor.cpp
  src/lib/Handset/CRSFHandset.cpp
  src/lib/Handset/devHandset.cpp
  src/lib/LED/devLED.cpp
  src/lib/LED/devRGB.cpp
  src/lib/LUA/rx_devLUA.cpp
  src/lib/LUA/tx_devLUA.cpp
  src/lib/MSPVTX/devMSPVTX.cpp
  src/lib/POWERMGNT/POWERMGNT.cpp
  src/lib/POWER_DETECT/devPDET.cpp
  src/lib/SCREEN/devScreen.cpp
  src/lib/SCREEN/menu.cpp
  src/lib/SerialUpdate/devSerialUpdate.cpp
  src/lib/ServoOutput/devServoOutput.cpp
  src/lib/THERMAL/devThermal.cpp
  src/lib/VTX/devVTX.cpp
  src/lib/VTXSPI/devVTXSPI.cpp
  src/lib/WIFI/devWIFI.cpp
  src/src/rx-serial/devSerialIO.cpp
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: V4.0 :hamburger:, house keeping :broom:

#3007 Allow setting 2400 domain for LR1121
  src/python/build_flags.py
Labels: bugfixes :lady_beetle:, V4.0 :hamburger:

#3040 Clean up target list order
  src/targets/unified.ini
Labels: V4.0 :hamburger:, house keeping :broom:

#3081 Fix: Minor issues in conversion of Mavlink to CRSF
  src/lib/MAVLink/MAVLink.cpp
Labels: bugfixes :lady_beetle:, V4.0 :hamburger:

#3017 Replace second packet memcmp with crc
  src/lib/LR1121Driver/LR1121.cpp
  src/lib/LR1121Driver/LR1121.h
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/SX127xDriver/SX127x.h
  src/lib/SX1280Driver/SX1280.cpp
  src/lib/SX1280Driver/SX1280.h
  src/lib/SX12xxDriverCommon/SX12xxDriverCommon.h
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: V4.0 :hamburger:

#3019 Set SetPPMoffsetReg for both radios on Team900 diversity hardware
  src/lib/LR1121Driver/LR1121.cpp
  src/lib/LR1121Driver/LR1121.h
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/SX127xDriver/SX127x.h
  src/lib/SX1280Driver/SX1280.cpp
  src/lib/SX1280Driver/SX1280.h
  src/src/rx_main.cpp
Labels: V4.0 :hamburger:

#3037 Double MSP (TLM and MAVLink) throughput for Gemini hardware
  src/lib/LR1121Driver/LR1121.cpp
  src/lib/LR1121Driver/LR1121.h
  src/lib/OTA/OTA.h
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/SX127xDriver/SX127x.h
  src/lib/SX1280Driver/SX1280.cpp
  src/lib/SX1280Driver/SX1280.h
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: V4.0 :hamburger:

#3039 Communicate Rx available antenna mode to the Tx
  src/lib/OTA/OTA.h
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: V4.0 :hamburger:

#3078 Allow choosing the RF Band on LR1121 modules
  src/lib/LUA/tx_devLUA.cpp
Labels: enhancement :magic_wand:, V4.0 :hamburger:
