Repository ExpressLRS/ExpressLRS, pull requests merged in 2024-04, with the labels that each got.

#2622 Fix antenna value for Diversity/Gemini receivers
  src/src/rx_main.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2617 Fix LR1121 binding
  src/include/common.h
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2616 Adds LR1121 image calibration
  src/lib/FHSS/FHSS.h
  src/lib/LR1121Driver/LR1121.cpp
  src/lib/LR1121Driver/LR1121.h
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/SX127xDriver/SX127x.h
  src/lib/SX1280Driver/SX1280.cpp
  src/lib/SX1280Driver/SX1280.h
  src/lib/WIFI/devWIFI.cpp
  src/src/rx_main.cpp
  src/src/tx_main.cpp
  src/test/test_embedded/rx_sx1280_test.cpp
  src/test/test_embedded/tx_sx1280_test.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2598 Add flag to encode string as raw string to fix deprecation warning
  src/python/build_flags.py
Labels: house keeping :broom:

#2615 Pass through handset channels if headtracking switch is off
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2631 HoTT Telemetry: robustness measure
  src/src/rx-serial/SerialHoTT_TLM.cpp
  src/src/rx-serial/SerialHoTT_TLM.h
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2630 LUA: prevent multiple I2C SCL/SDA selections
  src/lib/LUA/rx_devLUA.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2480 Add BMP280/BME280 I2C barometer support
  src/lib/Baro/baro_base.cpp
  src/lib/Baro/baro_base.h
  src/lib/Baro/baro_bmp085.cpp
  src/lib/Baro/baro_bmp085.h
  src/lib/Baro/baro_bmp085_regs.h
  src/lib/Baro/baro_bmp280.cpp
  src/lib/Baro/baro_bmp280.h
  src/lib/Baro/baro_bmp280_regs.h
  src/lib/Baro/baro_spl06.cpp
  src/lib/Baro/baro_spl06.h
  src/lib/Baro/devBaro.cpp
  src/lib/Baro/devBaro.h
  src/python/build_flags.py
Labels: enhancement :magic_wand:, V3.4 🍟

#2638 Fix SX1280 and LE1121 power setting
  src/lib/LR1121Driver/LR1121.h
  src/lib/SX1280Driver/SX1280.h
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2640 prevent WaitOnBusy from waiting on non-existing radio
  src/lib/LR1121Driver/LR1121_hal.cpp
  src/lib/SX1280Driver/SX1280_hal.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2637 Fix PWM section layout in web UI
  src/html/elrs.css
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2646 GH-2645 Disabled advertisement of default gateway to DHCP clients
  src/lib/WIFI/devWIFI.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2649 Added information about the target
  src/lib/WIFI/devWIFI.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2650 Fix the power-on-counter reset so it does not cause a connection loss at startup
  src/lib/ServoOutput/devServoOutput.cpp
  src/src/rx_main.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2643 LBT - change tx modules to use rxmode with timeout
  src/lib/LBT/LBT.cpp
  src/lib/LBT/LBT.h
  src/lib/SX1280Driver/SX1280.cpp
  src/lib/SX1280Driver/SX1280.h
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2621 [LR1121] Decrease PACKET_TO_TOCK_SLACK
  src/lib/LR1121Driver/LR1121.cpp
  src/lib/SX12xxDriverCommon/SX12xxDriverCommon.h
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2654 Remove generic targets from artifacts
  .github/workflows/build.yml
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2659 Save our help-and-support bretheren
  src/html/index.html
  src/python/serve_html.py
Labels: V3.4 🍟

#2633 Debounce BOOT0 readout in the hot loop
  src/lib/Backpack/devBackpack.cpp
Labels: V3.4 🍟

#2658 fixes HoTT Telemetry requiring an external diode
  src/include/targets.h
  src/src/rx-serial/SerialHoTT_TLM.cpp
  src/src/rx-serial/SerialHoTT_TLM.h
Labels: V3.4 🍟

#2663 adds previousMean() to MeanAccumulator
  src/lib/MeanAccumulator/MeanAccumulator.h
  src/src/rx_main.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2664 WORD_PADDED was returning number of words not bytes
  src/include/targets.h
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2666 add padding to buffer
  src/lib/LR1121Driver/LR1121_hal.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2665 S3 flash fix for binary_flasher
  src/python/binary_configurator.py
  src/python/binary_flash.py
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2660 Fix LBT TLM
  src/include/deferred.h
  src/include/rxtx_common.h
  src/lib/LUA/rx_devLUA.cpp
  src/lib/SCREEN/menu.cpp
  src/lib/WIFI/devWIFI.cpp
  src/src/rx_main.cpp
  src/src/rxtx_common.cpp
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2668 Hide button color editors in web UI
  src/html/scan.js
  src/lib/WIFI/devWIFI.cpp
  src/python/serve_html.py
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2670 Add missing LNA gain to the hardware.html page
  src/html/hardware.html
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2675 Fix TX logging with I2C
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2674 Fix boot-loop when no hardware definition uploaded
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2672 LBT 50hz RSSI settling time
  src/lib/LBT/LBT.cpp
  src/src/rx_main.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2680 Wait for multiple errors before stopping the wifi joystick
  src/lib/WIFI/wifiJoystick.cpp
  src/lib/WIFI/wifiJoystick.h
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2626 Allow MavFTP on the mavlink-rc branch
  src/src/rx-serial/SerialMavlink.cpp
Labels: MAVLink

#2629 Reduce mavlink buffer size, and disentangle airport buffers from mavlink
  src/lib/TelemetryProtocol/telemetry_protocol.h
  src/src/rx-serial/SerialMavlink.cpp
  src/src/rx-serial/SerialMavlink.h
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: MAVLink

#2682 Reset LQ to 100% on packet rate cycling
  src/lib/LQCALC/LQCALC.h
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: V3.4 🍟

#2684 Fix PWM issue of esp8266 device when duty is 0
  src/lib/PWM/PWM_ESP8266.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟
