Repository ExpressLRS/ExpressLRS, pull requests merged in 2024-11, with the labels that each got.

#3014 Maintain link connection on config.commit() for team900
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V3.5 🍩

#2998 Allow LR1121 single RF path
  src/include/common.h
  src/include/hardware.h
  src/include/target/Unified_ESP32_TX.h
  src/include/target/Unified_ESP8285_TX.h
  src/include/target/Unified_ESP_RX.h
  src/lib/CONFIG/config.cpp
  src/lib/LUA/tx_devLUA.cpp
  src/lib/OPTIONS/hardware.cpp
  src/lib/POWERMGNT/POWERMGNT.cpp
  src/lib/SCREEN/menu.cpp
  src/src/common.cpp
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: V3.5 🍩

#2960 Phase 2: More STM32 removal
  src/html/hardware.html
  src/html/index.html
  src/html/scan.js
  src/include/target/Unified_ESP32_TX.h
  src/include/target/Unified_ESP8285_TX.h
  src/include/target/Unified_ESP_RX.h
  src/lib/BUZZER/devBuzzer.cpp
  src/lib/BUZZER/devBuzzer.h
  src/lib/DAC/DAC.cpp
  src/lib/DAC/DAC.h
  src/lib/POWERMGNT/POWERMGNT.cpp
  src/lib/POWERMGNT/POWERMGNT.h
  src/lib/WIFI/devWIFI.cpp
  src/python/binary_flash.py
  src/src/dynpower.cpp
  src/src/tx_main.cpp
  src/user_defines.txt
Labels: V4.0 :hamburger:, house keeping :broom:

#3013 Fix Joystick mode to report as a "joystick" instead of a "gamepad"
  src/lib/BLE/devBLE.cpp
Labels: V3.5 🍩

#3016 Phase 3: STM32 Removal: Shared RX/TX parts
  src/include/target/Unified_ESP32_TX.h
  src/include/target/Unified_ESP8285_TX.h
  src/include/target/Unified_ESP_RX.h
  src/include/targets.h
  src/lib/BUTTON/button.h
  src/lib/BUTTON/devButton.cpp
  src/lib/BUTTON/devButton.h
  src/lib/Baro/devBaro.cpp
  src/lib/Baro/devBaro.h
  src/lib/LED/devLED.cpp
  src/lib/LED/devLED.h
  src/lib/LED/devRGB.cpp
  src/lib/OPTIONS/EspFlashStream.cpp
  src/lib/OPTIONS/hardware.cpp
  src/lib/OPTIONS/options.cpp
  src/lib/OPTIONS/options.h
  src/lib/POWER_DETECT/devPDET.cpp
  src/lib/SCREEN/FiveWayButton/FiveWayButton.cpp
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/VTXSPI/devVTXSPI.cpp
  src/lib/WIFI/devWIFI.cpp
  src/lib/WIFI/devWIFI.h
  src/lib/WIFI/lr1121.cpp
  src/lib/WIFI/wifiJoystick.h
  src/src/rx_main.cpp
  src/src/rxtx_common.cpp
  src/src/tx_main.cpp
  src/user_defines.txt
Labels: V4.0 :hamburger:, house keeping :broom:

#3021 Merge bug fixes from 3.x.x to master
  .github/workflows/build.yml
  src/include/common.h
  src/include/hardware.h
  src/include/target/Unified_ESP32_TX.h
  src/include/target/Unified_ESP8285_TX.h
  src/include/target/Unified_ESP_RX.h
  src/lib/BLE/devBLE.cpp
  src/lib/CONFIG/config.cpp
  src/lib/LUA/rx_devLUA.cpp
  src/lib/LUA/tx_devLUA.cpp
  src/lib/OPTIONS/hardware.cpp
  src/lib/PWM/PWM_ESP32.cpp
  src/lib/SCREEN/menu.cpp
  src/lib/WIFI/devWIFI.cpp
  src/lib/WIFI/lr1121.cpp
  src/src/common.cpp
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: DO NOT SQUASH MERGE - Merge Commit

#2932 Send RF Mode Enum in place of RF Index in the Sync packet
  src/include/common.h
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/CONFIG/config_legacy.h
  src/lib/LUA/tx_devLUA.cpp
  src/lib/OTA/OTA.h
  src/src/common.cpp
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: V4.0 :hamburger:, OTA Breaking Change

#2993 Auto set True Diversity Rx into Diversity or Gemini mode based on Tx antenna mode
  src/lib/LUA/rx_devLUA.cpp
  src/lib/OTA/OTA.h
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: V4.0 :hamburger:, OTA Breaking Change

#2991 Add tlmConfirm to tlm_dl ota packet-structure
  src/lib/OTA/OTA.cpp
  src/lib/OTA/OTA.h
  src/lib/TelemetryProtocol/telemetry_protocol.h
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: V4.0 :hamburger:, OTA Breaking Change

#2994 Auto configure Rx OTA protocol from the Tx
  src/lib/OTA/OTA.h
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: V4.0 :hamburger:, OTA Breaking Change

#3027 Phase 5: STM32 Obliteration: RX device cleanup
  src/include/target/Unified_ESP32_TX.h
  src/include/target/Unified_ESP8285_TX.h
  src/include/target/Unified_ESP_RX.h
  src/include/targets.h
  src/lib/AnalogVbat/devAnalogVbat.cpp
  src/lib/AnalogVbat/devAnalogVbat.h
  src/lib/Baro/devBaro.cpp
  src/lib/Baro/devBaro.h
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/LUA/rx_devLUA.cpp
  src/lib/MSPVTX/devMSPVTX.cpp
  src/lib/SerialUpdate/devSerialUpdate.cpp
  src/lib/ServoOutput/DShotRMT.cpp
  src/lib/ServoOutput/DShotRMT.h
  src/lib/ServoOutput/devServoOutput.cpp
  src/lib/ServoOutput/devServoOutput.h
  src/lib/Telemetry/telemetry.cpp
  src/lib/VTXSPI/devVTXSPI.cpp
  src/lib/WIFI/devWIFI.cpp
  src/src/rx_main.cpp
Labels: V4.0 :hamburger:, house keeping :broom:

#3008 Adds optional arming method and provides contiguous proportional channels for all full-res modes
  src/lib/Handset/CRSFHandset.cpp
  src/lib/Handset/CRSFHandset.h
  src/lib/OTA/OTA.cpp
  src/lib/OTA/OTA.h
  src/src/rx-serial/SerialDisplayport.cpp
  src/test/test_ota/test_switches.cpp
Labels: enhancement :magic_wand:, V4.0 :hamburger:

#3035 Return TX to configured RF mode after binding
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V3.5 🍩

#3033 Phase 6: Final STM32 removal
  src/html/hardware.html
  src/include/hardware.h
  src/include/native.h
  src/include/target/Unified_ESP32_TX.h
  src/include/target/Unified_ESP8285_TX.h
  src/include/target/Unified_ESP_RX.h
  src/include/targets.h
  src/lib/CONFIG/config.cpp
  src/lib/Handset/CRSFHandset.cpp
  src/lib/LBT/LBT.cpp
  src/lib/LED/devRGB.cpp
  src/lib/LR1121Driver/LR1121.cpp
  src/lib/LUA/rx_devLUA.cpp
  src/lib/LUA/tx_devLUA.cpp
  src/lib/MSPVTX/devMSPVTX.cpp
  src/lib/OPTIONS/hardware.cpp
  src/lib/SCREEN/TFT/tftdisplay.cpp
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/SX1280Driver/SX1280.cpp
  src/lib/ServoOutput/devServoOutput.cpp
  src/lib/TCPSOCKET/tcpsocket.cpp
  src/lib/TCPSOCKET/tcpsocket.h
  src/lib/Telemetry/telemetry.cpp
  src/lib/WIFI/devWIFI.cpp
  src/lib/WIFI/lr1121.h
  src/lib/logging/logging.h
  src/platformio.ini
  src/src/common.cpp
  src/src/rx-serial/SerialCRSF.cpp
  src/src/rx-serial/SerialHoTT_TLM.cpp
  src/src/rx-serial/SerialHoTT_TLM.h
  src/src/rx_main.cpp
  src/src/tx_main.cpp
  src/targets/common.ini
  src/user_defines.txt
Labels: V4.0 :hamburger:, house keeping :broom:
