Repository ExpressLRS/ExpressLRS, pull requests merged in 2024-03, with the labels that each got.

#2583 Fixed VTX pwm array initialization for unified ESP32 targets
  src/lib/VTXSPI/devVTXSPI.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2586 Fix ESP32 S3 CRSF/PPM autodetect
  src/lib/Handset/AutoDetect.cpp
  src/lib/Handset/PPMHandset.cpp
  src/lib/Handset/PPMHandset.h
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2590 Add file drag-and-drop to webui update tab
  src/html/index.html
  src/html/scan.js
Labels: V3.4 🍟, house keeping :broom:

#2591 Fix frameAvailable race condition
  src/src/rx-serial/devSerialIO.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2176 Add basic teamrace model select via channel
  src/include/common.h
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/CrsfProtocol/crsf_protocol.h
  src/lib/DEVICE/device.cpp
  src/lib/LED/devLED.cpp
  src/lib/LED/devRGB.cpp
  src/lib/LUA/rx_devLUA.cpp
  src/lib/OTA/OTA.cpp
  src/src/common.cpp
  src/src/rx-serial/SerialSBUS.cpp
  src/src/rx-serial/devSerialIO.cpp
  src/src/rx_main.cpp
Labels: enhancement :magic_wand:, V3.4 🍟

#2588 PWM testing/fixes
  src/lib/PWM/PWM_ESP8266.cpp
  src/lib/PWM/waveform_8266.cpp
  src/lib/PWM/waveform_8266.h
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2589 Increase SX1276 SyncPktIntervalDisconnected for 25Hz
  src/src/common.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2612 Fix TX module PPM input seeing spurious channels
  src/lib/Handset/PPMHandset.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2619 Fix "Not set" UID badge in web UI
  src/html/scan.js
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2618 Allow choosing the domain for LR1121 modules
  src/html/hardware.html
  src/html/index.html
  src/python/build_html.py
  src/python/serve_html.py
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2601 SerialMavlink: fix high rate radio message, report true TX buffer, use MAVLink struct and comp and system IDs to consts
  src/src/rx-serial/SerialMavlink.cpp
  src/src/rx-serial/SerialMavlink.h
Labels: MAVLink

#2602 common.ini: update MAVLink version
  src/targets/common.ini
Labels: MAVLink

#2624 WebUI: prevent multiple I2C SCL/SDA selections
  src/html/scan.js
Labels: bugfixes :lady_beetle:, V3.4 🍟
