Repository ExpressLRS/ExpressLRS, pull requests merged in 2024-06, with the labels that each got.

#2716 Every 2s the C3 will pause between loop invocations
  src/src/rx_main.cpp
Labels: bugfixes :lady_beetle:, V3.5 🍩

#2714 Adds betaflight passthrough flashing for S3/C3
  src/lib/SerialUpdate/soc_support.h
  src/lib/SerialUpdate/stub_commands.cpp
  src/lib/SerialUpdate/stub_commands.h
  src/lib/SerialUpdate/stub_flasher.cpp
  src/lib/SerialUpdate/stub_flasher.h
  src/python/build_env_setup.py
Labels: enhancement :magic_wand:, V3.5 🍩

#2750 Fake progress time increase to 10s for ESP8285
  src/html/scan.js
Labels: V3.4 🍟

#2727 Lower webui config heap allocation on ESP32
  src/lib/WIFI/devWIFI.cpp
Labels: For Discussion :mega:, bugfixes :lady_beetle:, V3.4 🍟

#2740 VTXAdmin PitMode On using YAW channel to trigger
  src/lib/VTX/devVTX.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2605 Add optional secondary serial device to ESP32 receivers
  src/html/hardware.html
  src/html/index.html
  src/html/scan.js
  src/include/common.h
  src/include/hardware.h
  src/include/target/Unified_ESP_RX.h
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/LUA/rx_devLUA.cpp
  src/lib/OPTIONS/hardware.cpp
  src/lib/WIFI/devWIFI.cpp
  src/src/rx-serial/SerialHoTT_TLM.cpp
  src/src/rx-serial/SerialHoTT_TLM.h
  src/src/rx-serial/SerialSBUS.cpp
  src/src/rx-serial/SerialSBUS.h
  src/src/rx-serial/devSerial1IO.cpp
  src/src/rx-serial/devSerial1IO.h
  src/src/rx_main.cpp
Labels: enhancement :magic_wand:, V3.5 🍩

#2732 Upgrade JSON library
  src/lib/OPTIONS/hardware.cpp
  src/lib/OPTIONS/options.cpp
  src/lib/WIFI/devWIFI.cpp
  src/targets/common.ini
Labels: bugfixes :lady_beetle:, V3.5 🍩

#2754 Merge 3.4.2 into master
  src/html/index.html
  src/html/scan.js
  src/include/common.h
  src/lib/HWTIMER/ESP8266_hwTimer.cpp
  src/lib/VTX/devVTX.cpp
  src/lib/WIFI/devWIFI.cpp
  src/python/serve_html.py
  src/src/rx_main.cpp
Labels: DO NOT SQUASH MERGE

#2763 Extend HoTT TLM sensor search discovery period
  src/src/rx-serial/SerialHoTT_TLM.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2755 Fix config being corrupted on 8285 receivers
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/src/rx_main.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2756 Check file type being uploaded.
  src/html/index.html
  src/html/logo-template.svg
  src/html/scan.js
  src/python/build_html.py
  src/python/serve_html.py
Labels: house keeping :broom:, V3.5 🍩

#2781 Avoid potential divide by zero in LBT dynamic power
  src/src/dynpower.cpp
Labels: V3.4 🍟

#2779 Fire TXdone when TLM forced off too
  src/lib/LBT/LBT.cpp
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2753 MAVLink support for ELRS
  src/html/index.html
  src/include/common.h
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/LUA/rx_devLUA.cpp
  src/lib/LUA/tx_devLUA.cpp
  src/lib/MSP/msptypes.h
  src/lib/OPTIONS/options.cpp
  src/lib/OTA/OTA.h
  src/src/rx-serial/SerialMavlink.cpp
  src/src/rx-serial/SerialMavlink.h
  src/src/rx_main.cpp
  src/src/tx_main.cpp
  src/targets/common.ini
Labels: V3.5 🍩

#2780 clear all form data before updating hardware setting
  src/html/hardware.js
Labels: bugfixes :lady_beetle:, V3.5 🍩

#2785 Don't keep the binding phrase as a compile parameter
  src/python/build_flags.py
Labels: bugfixes :lady_beetle:, V3.5 🍩

#2786 bug: increase ESP8266 hwTimer::resume buffer
  src/lib/HWTIMER/ESP32_hwTimer.cpp
  src/lib/HWTIMER/ESP8266_hwTimer.cpp
  src/src/rx_main.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2794 Move mavlink dep to non-default section to remove warning
  src/targets/common.ini
Labels: house keeping :broom:, V3.5 🍩

#2798 Remove mav_ul
  src/lib/OTA/OTA.h
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: MAVLink, V3.5 🍩

#2799 Change rx to PROTOCOL_MAVLINK if mav packets are received
  src/src/rx_main.cpp
Labels: MAVLink, V3.5 🍩

#2800 Merge 3.4.3 into master
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/HWTIMER/ESP32_hwTimer.cpp
  src/lib/HWTIMER/ESP8266_hwTimer.cpp
  src/lib/LBT/LBT.cpp
  src/src/dynpower.cpp
  src/src/rx-serial/SerialHoTT_TLM.cpp
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: DO NOT SQUASH MERGE

#2803 LR1121 - Prevent rogue spi write when there is no radio2
  src/lib/LR1121Driver/LR1121.cpp
Labels: bugfixes :lady_beetle:, V3.5 🍩

#2772 Handset Communication Optimisations
  src/include/helpers.h
  src/lib/Handset/CRSFHandset.cpp
  src/lib/Handset/CRSFHandset.h
  src/lib/Handset/handset.h
  src/lib/LUA/rxtx_devLua.cpp
  src/lib/LUA/tx_devLUA.cpp
  src/lib/SCREEN/menu.cpp
  src/src/tx_main.cpp
Labels: enhancement :magic_wand:, V3.5 🍩

#2492 Adds Rx fan support
  src/include/target/Unified_ESP_RX.h
  src/lib/OPTIONS/options.cpp
  src/lib/OPTIONS/options.h
  src/lib/THERMAL/devThermal.cpp
  src/lib/THERMAL/rpm.cpp
  src/src/rx_main.cpp
Labels: enhancement :magic_wand:, V3.5 🍩

#2770 Improve tlm sends when using lbt
  src/src/rx_main.cpp
Labels: V3.5 🍩

#2808 Translate MAVLink telemetry to CRSF on the handset (rebased)
  src/lib/CrsfProtocol/crsf_protocol.h
  src/lib/MAVLink/MAVLink.cpp
  src/lib/MAVLink/MAVLink.h
  src/lib/MAVLink/ardupilot_protocol.h
  src/src/rx-serial/SerialHoTT_TLM.cpp
  src/src/tx_main.cpp
  src/targets/common.ini
Labels: enhancement :magic_wand:, MAVLink, V3.5 🍩

#2812 Correct diversity rx tlm radio selection for non LBT
  src/src/rx_main.cpp
Labels: V3.5 🍩
