Repository ExpressLRS/ExpressLRS, pull requests merged in 2024-09, with the labels that each got.

#2907 Allow tagged artifact uploads
  .github/workflows/build.yml
Labels: house keeping :broom:, V3.5 🍩

#2910 Remove automatic mavlink protocol detection (for now)
  src/src/rx_main.cpp
Labels: bug :bug:, V3.5 🍩

#2916 Fixes 3 issues with the displays
  src/lib/SCREEN/devScreen.cpp
  src/lib/SCREEN/menu.cpp
  src/lib/SCREEN/menu.h
Labels: bugfixes :lady_beetle:, V3.5 🍩

#2939 Fix ESP32 based PWM receivers in debug mode
  src/include/targets.h
Labels: bugfixes :lady_beetle:, V4.0, house keeping :broom:

#2872 Silence unused-variable warning
  src/lib/LED/devLED.cpp
Labels: V4.0, house keeping :broom:

#2937 Merge 3.5.0 into master
  .github/workflows/build.yml
  src/lib/Backpack/devBackpack.cpp
  src/lib/Backpack/devBackpack.h
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/Handset/AutoDetect.cpp
  src/lib/Handset/PPMHandset.cpp
  src/lib/LUA/rx_devLUA.cpp
  src/lib/LUA/tx_devLUA.cpp
  src/lib/MSP/msptypes.h
  src/lib/OPTIONS/options.cpp
  src/lib/SCREEN/devScreen.cpp
  src/lib/SCREEN/menu.cpp
  src/lib/SCREEN/menu.h
  src/lib/WIFI/devWIFI.cpp
  src/python/binary_flash.py
  src/src/rx-serial/SerialMavlink.cpp
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: DO NOT SQUASH MERGE

#2871 Silence unused-variable warning
  src/src/rx_main.cpp
Labels: V4.0, house keeping :broom:

#2931 Split RC data sending from polling and queued data sending
  src/src/rx-serial/SerialIO.h
  src/src/rx-serial/devSerialIO.cpp
  src/src/rx-serial/devSerialIO.h
  src/src/rx_main.cpp
Labels: V4.0

#2933 Update OTA_VERSION_ID to V4
  src/include/common.h
  src/lib/FHSS/FHSS.cpp
  src/test/test_crsf/test_crsf.cpp
Labels: V4.0, OTA Breaking Change

#2947 Suppress a "fatal" error when building from a commit hash
  src/python/elrs_helpers.py
Labels: V4.0, house keeping :broom:

#2949 Backport #2931 "Split RC data sending from polling and queued data sending"
  src/src/rx-serial/SerialIO.h
  src/src/rx-serial/SerialMavlink.cpp
  src/src/rx-serial/devSerialIO.cpp
  src/src/rx-serial/devSerialIO.h
  src/src/rx_main.cpp
Labels: pick, V3.5 🍩

#2950 Allow CRSF radios that don't provide a module type
  src/lua/elrsV3.lua
Labels: bugfixes :lady_beetle:, V3.5 🍩

#2944 Fix entering BLE screen display blowing out memory!
  src/lib/SCREEN/menu.cpp
Labels: bugfixes :lady_beetle:, V3.5 🍩

#2954 Fix allowed rf modes in tx lua
  src/lib/LUA/tx_devLUA.cpp
Labels: bugfixes :lady_beetle:, V3.5 🍩

#2948 Fix building generic targets with a local checkout
  src/python/binary_configurator.py
Labels: bugfixes :lady_beetle:, V4.0

#2943 Reduce jitter for CRSF RC packets on the receiver
  src/src/rx-serial/SerialCRSF.cpp
  src/src/rx-serial/SerialCRSF.h
  src/src/rx-serial/SerialIO.cpp
  src/src/rx-serial/SerialIO.h
  src/src/rx-serial/devSerialIO.cpp
  src/src/rx-serial/devSerialIO.h
  src/src/rx_main.cpp
Labels: enhancement :magic_wand:, V4.0

#2926 Arm DJI O3 directly from an ELRS receiver
  src/html/index.html
  src/include/common.h
  src/lib/LUA/rx_devLUA.cpp
  src/src/rx-serial/SerialDisplayport.cpp
  src/src/rx-serial/SerialDisplayport.h
  src/src/rx_main.cpp
Labels: enhancement :magic_wand:, V4.0

#2963 Fix the stubborn receiver restart case
  src/lib/StubbornReceiver/stubborn_receiver.cpp
  src/test/test_stubborn/test_stubborn.cpp
Labels: bugfixes :lady_beetle:, V3.5 🍩
