Repository ExpressLRS/ExpressLRS, pull requests merged in 2024-10, with the labels that each got.

#2966 Reset `useFEC` flag when using non-FSK modes
  src/lib/LR1121Driver/LR1121.cpp
Labels: bugfixes :lady_beetle:, V3.5 🍩

#2965 Prevent vtx msp on tx boot
  src/lib/VTX/devVTX.cpp
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V3.5 🍩

#2971 Merge bug fixes from 3.x.x to master
  src/lib/LR1121Driver/LR1121.cpp
  src/lib/LUA/tx_devLUA.cpp
  src/lib/SCREEN/menu.cpp
  src/lib/StubbornReceiver/stubborn_receiver.cpp
  src/lib/VTX/devVTX.cpp
  src/lua/elrsV3.lua
  src/src/rx-serial/SerialMavlink.cpp
  src/src/tx_main.cpp
  src/test/test_stubborn/test_stubborn.cpp
Labels: DO NOT SQUASH MERGE

#2980 Housekeeping: remove some compiler warnings
  src/lib/LED/devLED.cpp
  src/lib/WIFI/devWIFI.cpp
  src/lib/WIFI/lr1121.cpp
  src/src/rx_main.cpp
Labels: V3.5 🍩

#2988 Fix Airport communication
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V3.5 🍩

#2997 Fix STM32 flashing options
  .github/workflows/build.yml
  src/lib/OPTIONS/options.cpp
  src/python/binary_configurator.py
Labels: bugfixes :lady_beetle:, V3.5 🍩

#2999 LUA: Hide Protocol2 for receivers with no pin available for Serial2
  src/lib/LUA/rx_devLUA.cpp
Labels: bugfixes :lady_beetle:, V3.5 🍩

#2983 set OtaCrcInitializer to OTA_VERSION_ID during binding
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: V4.0 :hamburger:, OTA Breaking Change

#2979 Remove Serial1 MAVLink check; MAVLink is supported on Serial0 only
  src/lib/LUA/rx_devLUA.cpp
Labels: V3.5 🍩
