Repository ExpressLRS/ExpressLRS, pull requests merged in 2024-02, with the labels that each got.

#2538 Add second reset pin to SX1276 for consistency with SX1280
  src/lib/SX127xDriver/SX127xHal.cpp
Labels: V3.4 🍟, house keeping :broom:

#2457 Inform serial protocols of missing packets
  src/src/rx-serial/SerialAirPort.cpp
  src/src/rx-serial/SerialAirPort.h
  src/src/rx-serial/SerialCRSF.cpp
  src/src/rx-serial/SerialCRSF.h
  src/src/rx-serial/SerialHoTT_TLM.h
  src/src/rx-serial/SerialIO.h
  src/src/rx-serial/SerialNOOP.h
  src/src/rx-serial/SerialSBUS.cpp
  src/src/rx-serial/SerialSBUS.h
  src/src/rx-serial/SerialSUMD.cpp
  src/src/rx-serial/SerialSUMD.h
  src/src/rx-serial/devSerialIO.cpp
  src/src/rx-serial/devSerialIO.h
  src/src/rx_main.cpp
Labels: enhancement :magic_wand:, V3.4 🍟

#2463 Get thermal info from S3 if no LM75A
  src/include/targets.h
  src/lib/THERMAL/devThermal.cpp
  src/lib/THERMAL/thermal.cpp
Labels: enhancement :magic_wand:, V3.4 🍟

#2550 Allow setting the destination for CRSF MSP packets
  src/lib/CRSF/CRSF.cpp
  src/lib/CRSF/CRSF.h
  src/lib/LUA/tx_devLUA.cpp
  src/lib/VTX/devVTX.cpp
  src/test/test_msp/encapsulated_msp_tests.cpp
Labels: enhancement :magic_wand:, V3.4 🍟

#2535 Feature: PWM failsafe modes, like no-pulse, hold, and custom set position
  src/html/elrs.css
  src/html/index.html
  src/html/scan.js
  src/include/common.h
  src/lib/CONFIG/config.h
  src/lib/PWM/PWM_ESP8266.cpp
  src/lib/ServoOutput/devServoOutput.cpp
Labels: enhancement :magic_wand:, V3.4 🍟

#2553 Fix RGB on S3 ofter platform upgrade
  src/lib/LED/esp32rgb.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2557 Merge 3.x.x-maintenance to master
  src/lib/LUA/rx_devLUA.cpp
  src/lib/OTA/OTA.cpp
  src/lib/PWM/waveform_8266.cpp
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/SX127xDriver/SX127xRegs.h
  src/lib/SX1280Driver/SX1280.cpp
Labels: DO NOT SQUASH MERGE, V3.4 🍟, house keeping :broom:

#2558 Update github actions
  .github/workflows/artifacts.yml
  .github/workflows/build.yml
  .github/workflows/stale.yml
Labels: V3.4 🍟, house keeping :broom:

#2559 For MacOS, prioritise the `wchusbserial` devices
  src/python/serials_find.py
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2542 Allow all binding methods on RX
  src/.gitignore
  src/html/index.html
  src/html/scan.js
  src/include/common.h
  src/lib/BUTTON/devButton.cpp
  src/lib/BUTTON/devButton.h
  src/lib/Backpack/devBackpack.cpp
  src/lib/CONFIG/config.cpp
  src/lib/CONFIG/config.h
  src/lib/CONFIG/config_legacy.h
  src/lib/CrsfProtocol/crsf_protocol.h
  src/lib/GSENSOR/devGsensor.cpp
  src/lib/Handset/AutoDetect.cpp
  src/lib/Handset/CRSF.cpp
  src/lib/Handset/CRSF.h
  src/lib/Handset/CRSFHandset.cpp
  src/lib/Handset/CRSFHandset.h
  src/lib/Handset/handset.h
  src/lib/LED/devLED.cpp
  src/lib/LED/devRGB.cpp
  src/lib/LUA/lua.cpp
  src/lib/LUA/rx_devLUA.cpp
  src/lib/LUA/tx_devLUA.cpp
  src/lib/MSP/msptypes.h
  src/lib/OPTIONS/options.cpp
  src/lib/OPTIONS/options.h
  src/lib/SCREEN/menu.cpp
  src/lib/ServoOutput/devServoOutput.cpp
  src/lib/WIFI/devWIFI.cpp
  src/lib/WIFI/devWIFI.h
  src/python/binary_configurator.py
  src/python/build_flags.py
  src/src/common.cpp
  src/src/rx-serial/SerialCRSF.cpp
  src/src/rx_main.cpp
  src/src/rxtx_common.cpp
  src/src/tx_main.cpp
  src/user_defines.txt
Labels: enhancement :magic_wand:, V3.4 🍟

#2540 Gemini Xrossband (GemX) - LR1121 Driver
  src/html/hardware.html
  src/include/common.h
  src/include/hardware.h
  src/include/target/FM30_RX_MINI.h
  src/include/target/Unified_ESP32_TX.h
  src/include/target/Unified_ESP8285_TX.h
  src/include/target/Unified_ESP_RX.h
  src/include/targets.h
  src/lib/CONFIG/config.cpp
  src/lib/DEVICE/device.cpp
  src/lib/FHSS/FHSS.cpp
  src/lib/FHSS/FHSS.h
  src/lib/LR1121Driver/LR1121.cpp
  src/lib/LR1121Driver/LR1121.h
  src/lib/LR1121Driver/LR1121Driver.h
  src/lib/LR1121Driver/LR1121_Regs.h
  src/lib/LR1121Driver/LR1121_hal.cpp
  src/lib/LR1121Driver/LR1121_hal.h
  src/lib/LUA/rxtx_devLua.cpp
  src/lib/LUA/tx_devLUA.cpp
  src/lib/OPTIONS/hardware.cpp
  src/lib/POWERMGNT/POWERMGNT.cpp
  src/lib/SCREEN/display.cpp
  src/lib/SX1280Driver/SX1280.cpp
  src/lib/WIFI/devWIFI.cpp
  src/python/UnifiedConfiguration.py
  src/python/binary_configurator.py
  src/python/build_flags.py
  src/python/firmware.py
  src/src/common.cpp
  src/src/rx_main.cpp
  src/src/tx_main.cpp
  src/targets/common.ini
  src/targets/unified.ini
  src/test/test_fhss/test_fhss.cpp
Labels: enhancement :magic_wand:, V3.4 🍟

#2562 DEBUG_RCVR_LINKSTATS needs to work without DEBUG_LOG
  src/include/targets.h
  src/src/rx_main.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2566 Add ESP8285 900MHz TX Target
  src/include/target/Unified_ESP8285_TX.h
  src/targets/unified.ini
Labels: V3.4 🍟

#2571 Only call servo function if theres a change
  src/lib/ServoOutput/devServoOutput.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2568 Update the wifi power levels
  src/lib/WIFI/devWIFI.cpp
Labels: V3.4 🍟, house keeping :broom:

#2567 Fix error when radio chip failed to read
  src/include/common.h
  src/src/rx_main.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟
