Repository ExpressLRS/ExpressLRS, pull requests merged in 2024-05, with the labels that each got.

#2694 Fix for compilation error when verbose logging is enabled.
  src/src/rx_main.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2690 GemX Lua RF Mode Labels
  src/lib/LUA/rxtx_devLua.cpp
Labels: V3.4 🍟

#2692 Avoid redefined warning when enabling DEBUG_CRSF_NO_OUTPUT and DEBUG_RCVR_LINKSTATS in user_defines.txt
  src/include/targets.h
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2700 Once more... fix for LBT
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2703 Update rfmodelastcycled at the end of setup()
  src/src/rx_main.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2706 SBUS: failsafe mode Last Position stops SBUS output
  src/src/rx-serial/SerialSBUS.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2610 ESP32 C3 RX support
  src/lib/DEVICE/device.cpp
  src/lib/LED/esp32rgb.cpp
  src/lib/LUA/rx_devLUA.cpp
  src/lib/POWERMGNT/POWERMGNT.cpp
  src/lib/PWM/PWM_ESP32.cpp
  src/lib/RFAMP/RFAMP_hal.cpp
  src/lib/SPIEx/SPIEx.cpp
  src/lib/ServoOutput/devServoOutput.cpp
  src/lib/VTXSPI/devVTXSPI.cpp
  src/lib/WIFI/devWIFI.cpp
  src/lib/logging/logging.h
  src/python/UnifiedConfiguration.py
  src/src/rx_main.cpp
  src/targets/common.ini
  src/targets/unified.ini
Labels: enhancement :magic_wand:, V3.5 🍩

#2719 Only allow one push to a hash in artifactory
  .github/workflows/build.yml
Labels: house keeping :broom:, V3.5 🍩

#2721 All zeros is unbound, not just any zero!
  src/include/common.h
Labels: bug :bug:, V3.4 🍟

#2709 Adds LR1121 startCWTest
  src/html/cw.html
  src/html/cw.js
  src/lib/FHSS/FHSS.cpp
  src/lib/FHSS/FHSS.h
  src/lib/LR1121Driver/LR1121.cpp
  src/lib/SX127xDriver/SX127x.cpp
  src/lib/SX127xDriver/SX127x.h
  src/lib/WIFI/devWIFI.cpp
  src/python/build_html.py
  src/python/serve_html.py
Labels: enhancement :magic_wand:, V3.5 🍩

#2698 Add ESP32 S3 lr1121 targets
  src/targets/unified.ini
Labels: house keeping :broom:, V3.5 🍩

#2717 Add extra lines for larger screen (e.g. Jumper T15)
  src/lua/elrsV3.lua
Labels: enhancement :magic_wand:, V3.5 🍩

#2724 WebUI gzip reminder fix
  src/html/index.html
  src/python/serve_html.py
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2738 Add more captive portal junk
  src/lib/WIFI/devWIFI.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2728 Fix for ESP8285 RX as TX
  src/lib/HWTIMER/ESP8266_hwTimer.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2745 Prevent immediate leaving bind mode if initrate change pending
  src/src/rx_main.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟
