Repository ExpressLRS/ExpressLRS, pull requests merged in 2024-01, with the labels that each got.

#2536 Pick SSID with strongest RSSI in mesh networks with multiple identical SSIDs
  src/lib/WIFI/devWIFI.cpp
Labels: V3.4 🍟, house keeping :broom:

#2525 Disable processing MSPVTX commands if there is not SPIVTX
  src/lib/MSPVTX/devMSPVTX.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2515 VTX SPI output calibration routine and initial PWM value config
  src/html/hardware.html
  src/include/hardware.h
  src/include/target/Unified_ESP32_TX.h
  src/include/target/Unified_ESP_RX.h
  src/lib/MSPVTX/devMSPVTX.cpp
  src/lib/OPTIONS/hardware.cpp
  src/lib/VTXSPI/devVTXSPI.cpp
Labels: enhancement :magic_wand:, V3.4 🍟

#2523 Support CRSF bind command from betaflight
  src/lib/CRSF/CRSF.cpp
  src/lib/CrsfProtocol/crsf_protocol.h
  src/lib/Telemetry/telemetry.cpp
  src/lib/Telemetry/telemetry.h
  src/src/rx_main.cpp
Labels: enhancement :magic_wand:, V3.4 🍟

#2406 VTX - Workaround for 25 bit data transmission bug on S3.
  src/lib/VTXSPI/devVTXSPI.cpp
Labels: bugfixes :lady_beetle:, V3.4 🍟

#2520 Allow screen rotation for TFT screens
  src/lib/SCREEN/TFT/tftdisplay.cpp
Labels: enhancement :magic_wand:, V3.4 🍟
