Repository ExpressLRS/ExpressLRS, pull requests merged in 2025-01, with the labels that each got.

#3088 No MAVLink for you STM32!
  src/lib/LUA/lua.cpp
  src/lib/LUA/rx_devLUA.cpp
  src/src/rx-serial/SerialMavlink.cpp
  src/src/rx_main.cpp
Labels: bugfixes :lady_beetle:, V3.5 🍩

#3093 LR1121 init power config
  src/lib/LR1121Driver/LR1121.cpp
  src/lib/LR1121Driver/LR1121.h
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V3.5 🍩

#3028 Permanently arm DJI (or other MSP displayport) air units using an RX
  src/html/index.html
  src/lib/OPTIONS/options.cpp
  src/lib/OPTIONS/options.h
  src/src/rx-serial/SerialDisplayport.cpp
  src/src/rx-serial/SerialDisplayport.h
Labels: enhancement :magic_wand:, V4.0 :hamburger:

#3100 [MAVLINK] Handle invalid battery values
  src/lib/MAVLink/MAVLink.cpp
Labels: bugfixes :lady_beetle:, V3.5 🍩

#3086 [Telemetry] Support directly-attached GPS inputs to RX
  src/html/index.html
  src/include/common.h
  src/lib/LUA/rx_devLUA.cpp
  src/src/rx-serial/SerialGPS.cpp
  src/src/rx-serial/SerialGPS.h
  src/src/rx_main.cpp
Labels: enhancement :magic_wand:, V4.0 :hamburger:

#3107 Clean up MSP_STATUS for DJI O4
  src/src/rx-serial/SerialDisplayport.cpp
  src/src/rx-serial/SerialDisplayport.h
Labels: bugfixes :lady_beetle:, V4.0 :hamburger:

#3079 Fix SPI FC problem with looping connection loss, reestablishment
  src/lib/LUA/lua.h
  src/lib/LUA/tx_devLUA.cpp
  src/lib/VTX/devVTX.cpp
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V3.5 🍩

#3113 Add k modes to tx module display
  src/lib/SCREEN/display.cpp
Labels: V3.5 🍩

#3112 ADC sampling fix
  src/lib/ADC/devADC.cpp
  src/lib/ADC/devADC.h
  src/lib/POWER_DETECT/devPDET.cpp
  src/lib/SCREEN/FiveWayButton/FiveWayButton.cpp
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V3.5 🍩

#3115 Downgrade AWS CLI for R2 compatibility
  .github/workflows/build.yml
Labels: bugfixes :lady_beetle:, V3.5 🍩

#3114 Force Gemini Antenna mode when using dual band
  src/lib/LUA/tx_devLUA.cpp
  src/lib/SCREEN/menu.cpp
Labels: V3.5 🍩
