Repository ExpressLRS/ExpressLRS, pull requests merged in 2025-04, with the labels that each got.

#3170 LUA script: auto adapt display properties to screen resolution and font size for color displays.
  src/lua/elrsV3.lua
Labels: enhancement :magic_wand:, V3.5 🍩

#3181 Merge into master
  .github/workflows/build.yml
  src/html/index.html
  src/lib/ADC/devADC.cpp
  src/lib/ADC/devADC.h
  src/lib/CONFIG/config.h
  src/lib/LR1121Driver/LR1121.cpp
  src/lib/LR1121Driver/LR1121.h
  src/lib/LUA/lua.cpp
  src/lib/LUA/lua.h
  src/lib/LUA/rx_devLUA.cpp
  src/lib/LUA/tx_devLUA.cpp
  src/lib/MAVLink/MAVLink.cpp
  src/lib/POWER_DETECT/devPDET.cpp
  src/lib/SCREEN/FiveWayButton/FiveWayButton.cpp
  src/lib/SCREEN/display.cpp
  src/lib/SCREEN/menu.cpp
  src/lib/VTX/devVTX.cpp
  src/lua/elrsV3.lua
  src/python/BFinitPassthrough.py
  src/python/SerialHelper.py
  src/src/rx_main.cpp
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, DO NOT SQUASH MERGE - Merge Commit

#3137 Refactor crc8_dvb_s2 Function for Improved Readability and Maintainability
  src/lib/MSP/msp.cpp
Labels: V4.0 :hamburger:, house keeping :broom:

#3191 Fix the ADC device after the 3.x merge
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V4.0 :hamburger:

#3077 Mavlink to Ardupilot Custom Telemetry CRSF translation for Yaapu Telemetry Script
  src/lib/MAVLink/MAVLink.cpp
  src/lib/MAVLink/ardupilot_custom_telemetry.cpp
  src/lib/MAVLink/ardupilot_custom_telemetry.h
Labels: enhancement :magic_wand:, V4.0 :hamburger:

#3185 LUA: auto adjust display parameter only on EdgeTX radios
  src/lua/elrsV3.lua
Labels: bugfixes :lady_beetle:, V3.5 🍩

#3076 Pass HeadTracking Pan/Tilt/Roll back to EdgeTX
  src/lib/Backpack/devBackpack.cpp
  src/lib/Backpack/devBackpack.h
  src/lib/CONFIG/config.h
  src/lib/Handset/CRSFHandset.cpp
  src/lib/LUA/tx_devLUA.cpp
  src/src/tx_main.cpp
Labels: enhancement :magic_wand:, V4.0 :hamburger:
