Repository ExpressLRS/ExpressLRS, pull requests merged in 2025-03, with the labels that each got.

#2862 New binding storage mode: Administered
  src/html/index.html
  src/lib/CONFIG/config.h
  src/lib/LUA/rx_devLUA.cpp
  src/src/rx_main.cpp
Labels: enhancement :magic_wand:, V3.5 🍩

#3167 Fix Airport - TX module in Airport mode initialized to wrong baud rate
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V3.5 🍩

#3165 Fix Head Tracker Disable command not being sent
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V3.5 🍩

#3154 Prevent interference from calling RXdoneISR
  src/src/tx_main.cpp
Labels: bugfixes :lady_beetle:, V3.5 🍩

#3159 Fix ADC/Joystick when no handset connected
  src/lib/ADC/devADC.cpp
Labels: bugfixes :lady_beetle:, V3.5 🍩

#3164 Fixing BF4.6 passthrough incompatibility issue
  src/python/BFinitPassthrough.py
  src/python/SerialHelper.py
Labels: V3.5 🍩

#3162 Fix debug build
  src/src/rx_main.cpp
Labels: bugfixes :lady_beetle:, V3.5 🍩

#3123 Adhere to the CRSF spec for folders
  src/lib/LUA/lua.cpp
  src/lib/LUA/rx_devLUA.cpp
  src/lib/LUA/tx_devLUA.cpp
Labels: bugfixes :lady_beetle:, V3.5 🍩
